apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: main-mysql
  namespace: database
spec:
  images:
    vtctld: vitess/lite:latest
    vtadmin: vitess/vtadmin:latest
    vtgate: vitess/lite:latest
    vttablet: vitess/lite:latest
    vtbackup: vitess/lite:latest
    vtorc: vitess/lite:latest
    mysqld:
      mysql80Compatible: vitess/lite:latest
    mysqldExporter: prom/mysqld-exporter:v0.11.0
  cells:
    - name: zone1
      gateway:
        authentication:
          static:
            secret:
              name: vitess-main-cluster-config
              key: users.json
        replicas: 1
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 256Mi
      lockserver:
        etcd:
          dataVolumeClaimTemplate:
            storageClassName: local-path
  globalLockserver:
    etcd:
      dataVolumeClaimTemplate:
        storageClassName: local-path

  vitessDashboard:
    cells:
      - zone1
    extraFlags:
      security_policy: read-only
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  vtadmin:
    rbac:
      name: vitess-main-cluster-config
      key: rbac.yaml
    cells:
      - zone1
    apiAddresses:
      - http://localhost:14001
    replicas: 1
    readOnly: false
    apiResources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    webResources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  keyspaces:
    - name: leantime
      durabilityPolicy: none
      turndownPolicy: Immediate
      vitessOrchestrator:
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        extraFlags:
          recovery-period-block-duration: 5s
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-main-cluster-config
                key: init_db.sql
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  backupLocationName: main-mysql-backup
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                      enforce-tableacl-config: "true"
                      queryserver-config-enable-table-acl-dry-run: "false"
                      queryserver-config-strict-table-acl: "true"
                      table-acl-config: /vt/acl/leantime.json
                      # table-acl-config-reload-interval: 50
                    resources:
                      limits:
                        memory: 1024Mi
                      requests:
                        cpu: 300m
                        memory: 256Mi
                  mysqld:
                    resources:
                      limits:
                        memory: 1024Mi
                      requests:
                        cpu: 300m
                        memory: 512Mi
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    storageClassName: local-path
                    resources:
                      requests:
                        storage: 10Gi
                  extraVolumes:
                    - name: acl-config-vol
                      configMap:
                        name: vitess-main-cluster-acl-config
                  extraVolumeMounts:
                    - name: acl-config-vol
                      mountPath: /vt/acl
    - name: seahub_db
      durabilityPolicy: none
      turndownPolicy: Immediate
      vitessOrchestrator:
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        extraFlags:
          recovery-period-block-duration: 5s
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-main-cluster-config
                key: init_db.sql
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  backupLocationName: main-mysql-backup
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                      enforce-tableacl-config: "true"
                      queryserver-config-enable-table-acl-dry-run: "false"
                      queryserver-config-strict-table-acl: "true"
                      table-acl-config: /vt/acl/seahub_db.json
                      # table-acl-config-reload-interval: 50
                    resources:
                      limits:
                        memory: 256Mi
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  mysqld:
                    resources:
                      limits:
                        memory: 1024Mi
                      requests:
                        cpu: 100m
                        memory: 128Mi
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    storageClassName: local-path
                    resources:
                      requests:
                        storage: 10Gi
                  extraVolumes:
                    - name: acl-config-vol
                      configMap:
                        name: vitess-main-cluster-acl-config
                  extraVolumeMounts:
                    - name: acl-config-vol
                      mountPath: /vt/acl
    - name: onlyoffice
      durabilityPolicy: none
      turndownPolicy: Immediate
      vitessOrchestrator:
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        extraFlags:
          recovery-period-block-duration: 5s
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-main-cluster-config
                key: init_db.sql
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  backupLocationName: main-mysql-backup
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                      enforce-tableacl-config: "true"
                      queryserver-config-enable-table-acl-dry-run: "false"
                      queryserver-config-strict-table-acl: "true"
                      table-acl-config: /vt/acl/onlyoffice.json
                      # table-acl-config-reload-interval: 50
                    resources:
                      limits:
                        memory: 256Mi
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  mysqld:
                    resources:
                      limits:
                        memory: 1024Mi
                      requests:
                        cpu: 100m
                        memory: 128Mi
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    storageClassName: local-path
                    resources:
                      requests:
                        storage: 2Gi
                  extraVolumes:
                    - name: acl-config-vol
                      configMap:
                        name: vitess-main-cluster-acl-config
                  extraVolumeMounts:
                    - name: acl-config-vol
                      mountPath: /vt/acl
    - name: seafile_db
      durabilityPolicy: none
      turndownPolicy: Immediate
      vitessOrchestrator:
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        extraFlags:
          recovery-period-block-duration: 5s
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-main-cluster-config
                key: init_db.sql
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  backupLocationName: main-mysql-backup
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                      enforce-tableacl-config: "true"
                      queryserver-config-enable-table-acl-dry-run: "false"
                      queryserver-config-strict-table-acl: "true"
                      table-acl-config: /vt/acl/seafile_db.json
                      # table-acl-config-reload-interval: 50
                    resources:
                      limits:
                        memory: 256Mi
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  mysqld:
                    resources:
                      limits:
                        memory: 1024Mi
                      requests:
                        cpu: 100m
                        memory: 128Mi
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    storageClassName: local-path
                    resources:
                      requests:
                        storage: 2Gi
                  extraVolumes:
                    - name: acl-config-vol
                      configMap:
                        name: vitess-main-cluster-acl-config
                  extraVolumeMounts:
                    - name: acl-config-vol
                      mountPath: /vt/acl
    - name: ccnet_db
      durabilityPolicy: none
      turndownPolicy: Immediate
      vitessOrchestrator:
        resources:
          limits:
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        extraFlags:
          recovery-period-block-duration: 5s
      partitionings:
        - equal:
            parts: 1
            shardTemplate:
              databaseInitScriptSecret:
                name: vitess-main-cluster-config
                key: init_db.sql
              tabletPools:
                - cell: zone1
                  type: replica
                  replicas: 2
                  backupLocationName: main-mysql-backup
                  vttablet:
                    extraFlags:
                      db_charset: utf8mb4
                      enforce-tableacl-config: "true"
                      queryserver-config-enable-table-acl-dry-run: "false"
                      queryserver-config-strict-table-acl: "true"
                      table-acl-config: /vt/acl/ccnet_db.json
                      # table-acl-config-reload-interval: 50
                    resources:
                      limits:
                        memory: 512Mi
                      requests:
                        cpu: 100m
                        memory: 256Mi
                  mysqld:
                    resources:
                      limits:
                        memory: 1024Mi
                      requests:
                        cpu: 100m
                        memory: 128Mi
                  dataVolumeClaimTemplate:
                    accessModes: ["ReadWriteOnce"]
                    storageClassName: local-path
                    resources:
                      requests:
                        storage: 2Gi
                  extraVolumes:
                    - name: acl-config-vol
                      configMap:
                        name: vitess-main-cluster-acl-config
                  extraVolumeMounts:
                    - name: acl-config-vol
                      mountPath: /vt/acl

  backup:
    engine: xtrabackup
    locations:
      - name: main-mysql-backup
        s3:
          authSecret:
            name: vitess-main-cluster-config
            key: s3_backup_secret
          bucket: hc-vitess-main
          forcePathStyle: true
          endpoint: https://${SECRET_CLOUDFLARE_ACCOUNT_ID}.r2.cloudflarestorage.com
          region: auto
  updateStrategy:
    type: Immediate
