---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: database
resources:
  - ./acl-config.yaml
  - ./secret.sops.yaml
  - ./cluster.yaml
  - ./service.yaml
  - ./schedule-backup-job.yaml
