---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: main-mysql-leantime-backup-job
  namespace: database
spec:
  schedule: "0 */12 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 50000
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backup
              image: vitess/lite:latest
              command:
                [
                  "sh",
                  "-c",
                  "/vt/bin/vtctldclient BackupShard --server main-mysql-vtctld.database.svc.cluster.local:15999 leantime/-",
                ]
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: main-mysql-seafile-backup-job
  namespace: database
spec:
  schedule: "0 */12 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 1
      ttlSecondsAfterFinished: 50000
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: backup
              image: vitess/lite:latest
              command:
                [
                  "sh",
                  "-c",
                  "/vt/bin/vtctldclient BackupShard --server main-mysql-vtctld.database.svc.cluster.local:15999 seafile/-",
                ]
