apiVersion: v1
kind: Secret
metadata:
    name: mosquitto-secret
    namespace: broker
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:mQ9EMA==,iv:10ofgZOk+BQ+oVUyOwM7JyEufGlzRmXdy4h26J6ZG3E=,tag:U1I3Ir6/6NVRaEojlOXPYA==,type:str]
    password: ENC[AES256_GCM,data:YenXBUrxXFVWXVlgOGQ8oA==,iv:SIOBkD6ST4306mKR4iK14/xtLy2TA+lgpjoBQvnBi90=,tag:Ueqkp9ymLlXwNNOSpMzglQ==,type:str]
    mosquitto_pwd: ENC[AES256_GCM,data:x+9OmpfRBASS0RDmw4icc9W8rKyzqw==,iv:BDTjTBML2RajFiFTOmRt3X/6smwe7EezEVt+0OvLnYc=,tag:aHSiBcwwoyh0mft2xSpwxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ak1YREVWaExOSlhQdHY2
            eEJrbkxuN2w5ZlpLb2p5K1ZKTjB0dUtyNmtrCkVnR1d5Q2wvcFpxREFTR0J5Y25X
            MmNoTlJTU3FHM0U2NjlVa1M2N3htdzAKLS0tIEN3WC9panVjajRQeGVDaVd2VTdC
            SmpXTjBpcWc3YUkrZUVIaFhEY0dLUWsKnjATWrFkR+cyBIiCj4wS5mbLyMh4niSS
            l6gPYoItK7WggTAa+AQl8eeSxbvAPufT4mpSrHsUKuK7gJ+zaeI5oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T07:46:59Z"
    mac: ENC[AES256_GCM,data:DrzJUXLHUMQfOfqcxjXtzlRKtu0NzImp+D7/uIITjoWSzTwmKoRdb3nkyyP1Cjfg/HHWfD/KJeCz7B4ebiqmPRrqQQI87Fx2YHynneUN0ignDxGH/LXQ7s0jKhH4XBSeUGo9Lsh71/U9ZFfpJsnq7gV2ZxTDpoNilMwxcywnBwE=,iv:qf3bdZrt80TZHFe+Ynu4dsEF8OYFzXmulmrzS/Y1L7A=,tag:Y6RlfLgh9a8S1KgLL6BdEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
