# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: trarcar-configuration
data:
    traccar.xml: ENC[AES256_GCM,data:LZ5gVNZJEmz2ZejOBal7UxCwZPG+CBe+aRsn673qyOATvFHPV2terkwO97VdJDQ/qB5izT6GwdLNeEnpgXEQO3YVyMq8MHxjBUNTeRpMRgEoUfxDA32+mJNbuT/BA7hBqId7VEjK08MSAqeKx/AJ7iNRIKL+zMvakcJUVV9bu4sGUkr/wCbc9WX8CxvoGL6sXeEI+eKrhxj33Ry4DLqlcH+2zKY1SOmRUSeH5rAG6C/tDEqBtTPVYzX6x4MaqP+0BUFJek+wFEQFH+rrquDpLGJWS2ql0+idcmt+QKm9gePjoww8QANtGNSTtw0mh+C27Hxz5FvNaK5ImvxrB+7LK4GU0DpQ1bIEfmtirGCWXHBpQbFviyZ6KXYbJ0e+qdkqeavJtFK7y6g7POykYZt57XAYrbkKNtJbJqyAgN9X9VYUBvSKcasqSbjVr/o5xaMGspOyjSus9V9bOa1MqiydssvH+NepnoPHg2zjtdTmcO3fCy6i0DLsxCvmHbbaT61zgDFDbI/BCDvc1S3tQjNO6ro2+vk4+79vP9LrKAHZE2GIwz2JNQcU34uUtBmviscQlnu7Bqg9sO7gYojmjwEXdoA0JRJoM9cdGoON8phUrZumHOOo4f8DcBkCB3v1FY5ao1o=,iv:p5NceU10LrCSeW/Xto2yTAQa1OUh1IzlIuIe2/nazEw=,tag:IJ/GXYV0xxmK5ywG9C1E5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T12:42:53Z"
    mac: ENC[AES256_GCM,data:wn/t/MwVkW2SRzw9JHrUSjeh9Bpi4/kscZ8EXckZvB6HqFt1uT49ixoa4+kzoiX5hcj2PwQy7YwEZr+MdNlREKmAzOfAl+YPBXm7Yj4HjCCQvIzwNxKyUJEVbh9UpKb1AqQX3EVYjebSXbU7xfHYKVhyfAyqwKuk5QinxhtCcRA=,iv:uAfXSSkEA9p9OUqFoVaSM8Ch7wZ6TcOxKTNfXl3azlk=,tag:gv+F78TTvACzefmaHUvMaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
