# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: trarcar-configuration
stringData:
    traccar.xml: ENC[AES256_GCM,data:3YuNjPZtjrzDq6vp4yNRglbUuuwthFPY7NHwMqxD6ljBSGZkaQC9e3eEkR6hHs71qGQabMODbR4gbiBUgm+ij128K/BFadzwMYJ/UPOHiPRjI8yuOKM14fbGvY0wGaz5+/c0rks4Re/eiB1dykMbxQFe6m/XxoQq4MTOXlmfQd8s6RBqPKEPAd91u6ycs9e5JjXDvh8gvRRC8RsWFI94sDBVwU9JQKlXH4APWf0yo4Wlb/Fy+0g5eaaCz3LQkBa6vDBIJlNod5vo6QFrm+s80kSFPdSIMAhuU69L+yLRZYLxocegcXSnmGdWDegCUr1efTvdpGS/u51hHCBeOz5snhWONJJNlfjlMzcTgLwoth4Il+iatFJr2Adym7ES4mIb8YmABkG/DaDDdPGwqqN+hZFnHf5MWTCtcvLbibH+5tzYEOL1pLhWPHPFysjCaRWV5xtlwVrUtI4IvarbGi3HSJIVKXgmi2oa+2xs+HP1WRRTnVQRR4MUFUm/e9LHKlxZ2Yt8N+MQp0iKrHC4XkzkIW4MWpl51CXbPuGawrSbrwKjyOrTVv7jGgOmkUbFDwGfJn+yHyZEwJpfRIwGYXhkititJfG2gemTU99mJ5Sy7Z4Dbr3uEPuTDdyk7pQ3sj7+oEI=,iv:X5u5f/6wxd+WOBetH/W7Gej1EDZgOiMLUSPx04JDodc=,tag:h9hBIUo8xdvdbKcXQuTj1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-22T12:54:53Z"
    mac: ENC[AES256_GCM,data:bvFT0UC2f8OZwauMjD+Q3BsQg+PL4St9TOmcxu2OXKZEE15c4+xzzTcAdtmFNRe8hLo4N0nJOOvJisSbwceXhORTGLLknI0f/LC7GZjUrN0a4rOLFbETgojkNvP3zN25umh9hON+xwQ96ijSMCf5y36olixBC2KPIoNSSnEv3p0=,iv:B8tytdqRpoG1eoviS0gfP9GZZRolBy0lUgW5MzChySg=,tag:S4KL+KFG9cUKOEg+vImsgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
