apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-data
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-zfs-1
  resources:
    requests:
      storage: 500Gi # Size does not matter
