# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: omnivore-migrate-env-secrets
stringData:
    PG_USER: ENC[AES256_GCM,data:MnfD0gLs390=,iv:SzxstEpzj3lvz+7PwuRun5Kpu97lfG+eKwMlJ1H4GbQ=,tag:7/9SYhGAEzkjXC0q/+AwSw==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:ix/07X49g+oB110RdK6xcQ==,iv:KvVDArHEQZ96LvW+OX6iyGTuAEZoU4vAkDGpVE9N6Kc=,tag:nQGvGlkBbSTM5jb0QZYVAQ==,type:str]
    PG_HOST: ENC[AES256_GCM,data:R0k0LEw9RYn/tENG8Oj5xw4GhfXhx51Sq+RPnU8xJMkqvt1IpCc=,iv:D8LAV6RNT2BOHBMUELUWRiFa22ukzg06LPnR23OxWvc=,tag:GSjF70BjR1E4SaqnhYJGfw==,type:str]
    PG_DB: ENC[AES256_GCM,data:DqqbA0tTeSQ=,iv:Nbg2qa2d9i3uHHIA6Qm5AstAvLIqwjUCGv60oNo6+c4=,tag:M9fJAG1aDpnP2y5ay/E+kw==,type:str]
    PG_PORT: ENC[AES256_GCM,data:yjgPQw==,iv:n5I1xL2XfT0UXX7Tb6wMcOVQ5YoNkedk2DXh2GPsCGw=,tag:6zVwpNVYt1x0QBY664wVVQ==,type:str]
    PG_POOL_MAX: ENC[AES256_GCM,data:mjc=,iv:68eiL/kQ5mtkNkZ1Rr/wSR3aapzWEcdyRQobK3tXESo=,tag:3vzPEZ3U9yrW2Zzarfbt2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T06:57:52Z"
    mac: ENC[AES256_GCM,data:LJbwk5MXnc5n10COdOZhITCXhFD99rDA1p7DFaxFuCNFjVIfeJbk8Qbhrh7uV25enkn6erZvMQFKC5d5xEmBu8UDKfAd0+iR6TydpcV9liuucotQuS5feo1sZPjTgAbEfESO8vDM2AtyRdexWMhoc9dubi9NUSjKxr+9GqWXwxA=,iv:uSuSOM31JOC5k+ckAOwNkqrL8pXCIG6lxS7/9sOOJMM=,tag:Vh/paLseFH/rxRhXFFOAfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
