# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: omnivore-migrate-env-secrets
stringData:
    API_ENV: ENC[AES256_GCM,data:W44Jo0c=,iv:imPaK87mpr1u6VidqdKWXTtoONIPLYLqwbdMFNt+yyQ=,tag:wRkvBZ5QM3YArqiwkfASGQ==,type:str]
    PG_HOST: ENC[AES256_GCM,data:4bMZ9YuoVKw0fwux6anhOO70iTecVxdbjt2Xm+NCOujA6G8rMs0=,iv:igFDEaCWDCsGgn1Rn7hPQlboZZlUiWvbSSq9ezrMYoI=,tag:turBvSTOwyo7qalOj3uM8g==,type:str]
    PG_USER: ENC[AES256_GCM,data:lEL3uuGdpu8=,iv:cMhiPutvIei4PaQO5AALYRhok8G3zFGaAXb7c/ZjyJc=,tag:vO7+N8whOUhj3NRKOTSfgA==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:TFiKXDoDfixJ+a+bHRPWMA==,iv:CIZDxkUwCN1L1sas1EanuRaKJ0zqLuN+2mScTopIrm0=,tag:AESVnn9+dWZMxH9WKnKjlw==,type:str]
    PG_DB: ENC[AES256_GCM,data:BBGmFPevqz4=,iv:h58u4v8PPgwBtUGn/oCPSL6VkX7VVhuN9mpWupnR/aU=,tag:TTN4QLRlP7oUGPh1HWoGKw==,type:str]
    PG_PORT: ENC[AES256_GCM,data:S+TgGQ==,iv:8gdlo8i/0ys8PrnoSgQycFn3lHt3UWNjT67AcOZ+DHQ=,tag:3xDM5RB5n6RFEJU7b1D1bQ==,type:str]
    PG_POOL_MAX: ENC[AES256_GCM,data:Wdg=,iv:wcVR88xDrj4HjMfdUiqOiXZIKa6zIqAfp4avbyDFoBs=,tag:EOdioQrvRbqRObvj3PrzIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T04:46:56Z"
    mac: ENC[AES256_GCM,data:0QhFBwEbDJpQu3OVvFDMcBCFS1H1TPDt0VKpTBjQUw5hIEz7vljQrAqX0cUp6vIQX3meOZEAsbSWvgXH7RrLeM1x/YeBM2EovnQbqpahDmG7VVPzVP3b0EYEgoIJXRxA8gFjlL6Rg+DvPEXNb1yoOI2Z53zNx8KtEqA0r3rSDEM=,iv:QU9wrNMnCG54wIEdKnSXAlPiPmXA/EPQHX3vcVoOkYk=,tag:lhZUkvlN/utj9EihR2x07g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
