# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: omnivore-env-secrets
stringData:
    API_ENV: ENC[AES256_GCM,data:W44Jo0c=,iv:imPaK87mpr1u6VidqdKWXTtoONIPLYLqwbdMFNt+yyQ=,tag:wRkvBZ5QM3YArqiwkfASGQ==,type:str]
    PG_HOST: ENC[AES256_GCM,data:4bMZ9YuoVKw0fwux6anhOO70iTecVxdbjt2Xm+NCOujA6G8rMs0=,iv:igFDEaCWDCsGgn1Rn7hPQlboZZlUiWvbSSq9ezrMYoI=,tag:turBvSTOwyo7qalOj3uM8g==,type:str]
    PG_USER: ENC[AES256_GCM,data:xc5+gdeiAq0=,iv:TKThFnw7yOMeaTEYVeOY3LA1/FqgRhHgbWXxfVoxIvI=,tag:xYAfp6dhSSH107GiOE1wGw==,type:str]
    PG_PASSWORD: ENC[AES256_GCM,data:2WN/F76ysxQIOYiPNCU=,iv:vmVw5aueZ9uwVMzE+EFzPJ+L2E42RKkdPfQRlXYpMuw=,tag:hqtvzCSlhs7eYnugWUoP6w==,type:str]
    PG_DB: ENC[AES256_GCM,data:BBGmFPevqz4=,iv:h58u4v8PPgwBtUGn/oCPSL6VkX7VVhuN9mpWupnR/aU=,tag:TTN4QLRlP7oUGPh1HWoGKw==,type:str]
    PG_PORT: ENC[AES256_GCM,data:S+TgGQ==,iv:8gdlo8i/0ys8PrnoSgQycFn3lHt3UWNjT67AcOZ+DHQ=,tag:3xDM5RB5n6RFEJU7b1D1bQ==,type:str]
    PG_POOL_MAX: ENC[AES256_GCM,data:Wdg=,iv:wcVR88xDrj4HjMfdUiqOiXZIKa6zIqAfp4avbyDFoBs=,tag:EOdioQrvRbqRObvj3PrzIQ==,type:str]
    #ENC[AES256_GCM,data:4y89g9Oy0O/Owtdz7notqEyNXgaisn65d8XQzWtIaKENtcvTFnffgtezlQ==,iv:qZi9I/pDXEOr6LbYgWRFKTA7pXElkGtYA/MF0jcjnsQ=,tag:TeSJlL1YKC343zQ5SAd0CA==,type:comment]
    CLIENT_URL: ENC[AES256_GCM,data:lXpIaWX6DkHMJ4i34LmMTxiKUgYxLu1HAPC+,iv:T/MW4LzEYkXT7VG5U3b+qISeNRWUL22gw6tBaQzKgAs=,tag:dLWi/YHMvuz+F/G9rAz1qQ==,type:str]
    GATEWAY_URL: ENC[AES256_GCM,data:76seOmn/CkFc2yEVvFWXW8eXCC+ZxDjJ3TfaYFEfsOdXSs9kaFkP2NBxsND4w384ENVJwIND73tX+SqV,iv:0E3ILkRRWsqtWx7wbeOp3F8Clh731TEdvixPIEnIkpo=,tag:EWU64222knFeq2WtiuQkWQ==,type:str]
    CONTENT_FETCH_URL: ENC[AES256_GCM,data:LzwHTpVNTxUwW6qgNT0g+y28Lc7XnhDs188V849DnSkvbm7CpoonFbeWUKjP/8LPxJdwetpJDULzolsMt37zD+Y2btJH9qH1teOhlnkE5E2L4oQBCzvQvJntCeIcfJV7fawD0NGGBc3NTjd0r6VKd7nHekJ9Xv9xgkBB0O2BxeB94zIEiyvKbu4=,iv:s2MiRvvfita0r9IFspuJFyWtwuHk+6BTd4rIuWn9+5E=,tag:SeKK1knQLJev3VqqgDJkCw==,type:str]
    IMAGE_PROXY_SECRET: ENC[AES256_GCM,data:e8Qlb8Gutga6bqTh9n5LukHYpU6EOAvXOfY+JmKxSiXL95jL8+W2eTtQe9UfXGy7VrOFSs1+NzSW0WKMVMY4+g==,iv:B4tjNSqmT2qZjHxPmPwh3FA5PZoMaMDKprcKlbqbghc=,tag:HRFy150Odb4fI+wfVrUAvw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:fkNrD+yy4Ahzurv43Vy/ZshXv59fpTDnE7jigyZvUs8ieRif5IfCritiG9kUdFukRqoHw/H+2QjoRid55KFbpQ==,iv:AO9ECD4CcKL/5KDAA3u1URYhjz+pLF/gvI1lDFepJcw=,tag:ifXcTcCzn9SCO7gNDu/U3Q==,type:str]
    SSO_JWT_SECRET: ENC[AES256_GCM,data:ovJFGXZEWEIqkZgR2uFJ1tbaaTiO9tUyzW+kqoYy2FjM2hUoWIIr41chOZTCOnaTtWJOt9N+u0uIEYMg2mj8qg==,iv:iqahi7C91bde/jc9dDVNAJur65UguchSwKCINBG/BkA=,tag:qoaB+riK3vCoSbBrHU81cA==,type:str]
    VERIFICATION_TOKEN: ENC[AES256_GCM,data:ot1nmndjywUVoDa17NPmtN7h3Nu8HFVmzqDdo9UNmviiYPnTrXw+giRWfn+HoLqozOX3XThlDkJasIx+jBI6LQ==,iv:ckpZf1otmQuid5H7b+yrdgv+yWncxOqG/XKPE25lQs8=,tag:X4sjX7vObBmuNAIsGeY7Pg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:XIXpbFDYJIW7A/kPZ4pIvRFHPMGMyB17oRU3bu61xLiOXQ+T9asXl0fc34O06zqUD9ml8JAQnlqLTRfiqSwDrUQ=,iv:HGE2e3GG4Is4vR4qV9UcL+3gSz3zv2xiju/MHWQqwmE=,tag:aQhK02KFSR/eX0MFR1EGGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-04T04:37:33Z"
    mac: ENC[AES256_GCM,data:jqBJ4V9xCd7kSJPz0Nr2N+Lbc7MiMmG5cLORGJ4ftMgLiQBywX2vLqpZLWr0ZqxeVZuyCY055loJtvT5Zf01L0fyKtpUnawCN6J0jd8ti44q7/FUzNtciA5w+yqNwevAOWlGET06ANu1xClrox2zhAlrry8p0J7mKW5Jyt5kktk=,iv:+aJeMXH46dHrRSG/4nZCxIEWuxkc7Rbj4rUwVM2yUnA=,tag:xrGVMvPirx03uuzvocAs+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
