---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch-staging
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: elasticsearch
      version: 22.1.6
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    master:
      masterOnly: false
      replicaCount: 1
    data:
      replicaCount: 0
    coordinating:
      replicaCount: 0
    ingest:
      replicaCount: 0
