---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-egress-to-cluster
  namespace: coder-v2  # Replace with your target namespace
spec:
  podSelector:
    matchLabels:
      "coder-v2": "true"
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.99.0/24
              - 10.0.88.0/24
              - 10.0.100.0/24
              - 192.168.1.0/24
              - 192.168.89.0/24
              - 192.168.88.0/24
