---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-development-coder-v2
  namespace: flux-system
spec:
  targetNamespace: coder-v2
  path: ./kubernetes/apps/development/coder/v2
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
