# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: aitbotsync-redis-secrets
    namespace: business
stringData:
    redis-password: ENC[AES256_GCM,data:bgzUhi8vFeEObdbuMywe3Q==,iv:ZVOpucmj6sDtvvJoKwh+tv0friUtNF0ICuHEufI5kAA=,tag:bAPXBYnpLTDzV59OET5Eyg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-29T06:07:41Z"
    mac: ENC[AES256_GCM,data:YrG8vRdHIm27oBEOv6NyzK+RfeE2ARLZAKvoay8jrW8GB7zFpmF5jRzgpHsL4sGchPp3qYe0NivznLWdzp1rIz0k88JkzXrk/Ld27k4AgzSmvV/cdNaPE8T8f4qqe2+FDkQ90V8vOIGTayjBo+HddCibdRjD9ygu6Z9I4yzec5o=,iv:q/HtB6kt78zyu1+AvySNS9lrwUCwAt2apSGKdaMKd7M=,tag:K8p0D6QttKp1yax0VHsgIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
