---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app guild-server
  namespace: openmu-prod
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: imtoanle-ghcr-key
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: guild-server
        dapr.io/app-port: "8080"
    controllers:
      main:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/imtoanle/newmu-guild
              tag: 0.8.3.0
            env:
              APPID: guild-server
              ASPNETCORE_URLS: http://+:8080
              ASPNETCORE_ENVIRONMENT: Production
            # resources:
            #   requests:
            #     cpu: 200m
            #     memory: 300Mi
            #   limits:
            #     cpu: 2000m
            #     memory: 3000Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
          guild:
            port: 50001
          # Prometheus
          metrics:
            port: 9464
