---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app locatepin-app
  namespace: business
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      imagePullSecrets:
        - name: imtoanle-ghcr-key
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          # secret.reloader.stakater.com/reload: "chatwoot-vietwings-secret-envs"
        containers:
          main:
            image:
              repository: ghcr.io/imtoanle/locatepin-server
              tag: 0.0.2
              pullPolicy: Always
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8888
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            # resources:
            #   requests:
            #     cpu: 250m
            #     memory: 256Mi
            #   limits:
            #     cpu: 500m
            #     memory: 512Mi
      adminfe:
        replicas: 1
        annotations:
          # secret.reloader.stakater.com/reload: "chatwoot-vietwings-secret-envs"
        containers:
          main:
            image:
              repository: ghcr.io/imtoanle/locatepin-adminfe
              tag: 0.0.2
              pullPolicy: Always
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
            # resources:
            #   requests:
            #     cpu: 250m
            #     memory: 256Mi
            #   limits:
            #     cpu: 500m
            #     memory: 512Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8888
      adminfe:
        controller: adminfe
        ports:
          http:
            port: 8080

    serviceAccount:
      create: true

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          # nginx.ingress.kubernetes.io/configuration-snippet: |
          #   rewrite ^/api/(.*)$ /$1 break;  #重写
        hosts:
          - host: &host "locatepin.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: adminfe
                  port: http
              - path: /api
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: "configMap"
        name: "locatepin-backend-secrets"
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
