apiVersion: v1
kind: Secret
metadata:
  name: imtoanle-ghcr-key
  namespace: business
data:
  .dockerconfigjson: ENC[AES256_GCM,data:LdWN9U00joUxPj+CEBmFoN9E6YBwCq8GH6I4hO/7BIajJLth6fRTiMfUqq2GL1oNoVzL53CG68FMWN0A6atuk/Tb1q7j4u5Ho6ZnnEKYijOD4DGN1HqT1qOJO5AC9zTjMGsQPj+S+ifQJA7gS5BZhF+goqhjLH9kgF2r8tqd6gkWwCCt3S1HJA==,iv:05M5Gohp1rgCXL+TU1Y4m9/IPAbHQmKHN6Un+5Q6uzw=,tag:Zz/OtNXyF9UjVWsNPJmBTQ==,type:str]
type: kubernetes.io/dockerconfigjson
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpTTgzam9JZ2RJZjJtSmVM
        WFVBaE1kK3hQQldSV3NLZk9kM1MzdEkxdTJ3CmhpNG9DdGZQcEZSYlpmclppOEhE
        RnlMaXRCV0w0S1lxeDdwQTg4VEVBdGcKLS0tIHExZ1J2VkhuMSt4RGFWN3BHcU4v
        emF6Zm5yemlOaTg0K2loaUlHR010bEkKswyZFmFXnok/O54Cj2wDdBDgIP5GWb3z
        A4IipHp46RpleiquXDubChc1JLYpQhx6WkEm+pBCfLBDUpF9IEyvCg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-01-23T05:28:04Z"
  mac: ENC[AES256_GCM,data:s0aZMZ7TuB5qKTXk3Hjf6frGP7M1Rutg/5kP4EpADWuvX5mqmNFjUdS2ugT4Lralcrn+9U/3SuLYE6uaGTMWxsmWjf6A197Wl4bpWAhISi7WDjguQcL5W9Gy7SdEa7ebwFsIfwhZKf1qQQqq8n11cv6hO4RDNubq14MYUUEhMIo=,iv:fmVmiz0fZ/epmYElDBTdkxR4ittBUlw8c1XdbMaRMs0=,tag:FV/0EaQF2pm+wXGfDsy+fg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
