# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: kotaemon-env-secrets
stringData:
    GRADIO_SERVER_NAME: ENC[AES256_GCM,data:u5TH8v078w==,iv:+wIeS5bpEtk68p9IUQdJoZZ/4u6eh3HgVmxdGxF9k/Q=,tag:b8oe0435Qs+OmQik6eX/GQ==,type:str]
    GRADIO_SERVER_PORT: ENC[AES256_GCM,data:ecIweQ==,iv:wYOiK9DZ3LdJ8k6iX4cymsHb5jC85yk+DqxuzAmCXMY=,tag:gRZUGIKret/hLtBZ6nShkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T03:54:46Z"
    mac: ENC[AES256_GCM,data:7bwbiHNtfeUCNS55SN2jQJy5ChDoqp1RqWALpiu/jLDl682jAOr9fg8x2tK8EDVYkWl4Yve+gopbN01lDXBCZan/9DNSVSg+qKS/grc/YbycX6KLmaEJO2hK9YHdFRssw2NLNtPGOf771K5emtWM1k27BDDAl4ZAxXSG1yW2evw=,iv:2peyAdM9wHgH+wfR3MO/nvJ4AMLvh88JFY/KHZZ91mg=,tag:Uf7GqmAp4GOqVBOu5ABT0w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
