# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: openmu
stringData:
    DB_HOST: ENC[AES256_GCM,data:2EryWB0BvKah2qifOPeGwXle94JgQcvBRj0tud/NH2UPiv+1HsXcznamz81d,iv:FMpj3Fh+21Cz9PkXmoFBUYua2arPQVXbfIIlVZs/0Jc=,tag:jqXG7Z84VO879Oqe/NMPjg==,type:str]
    DB_ADMIN_USER: ENC[AES256_GCM,data:AB+gKVlztcg=,iv:WfErnnnASxlVUFsNx1lYUfeHEwp2gTPR4c1hSF4ifr8=,tag:GfhbqgZMk2Df6tGYn70HOA==,type:str]
    DB_ADMIN_PW: ENC[AES256_GCM,data:vc7vslYOekjEMiMvxkw=,iv:my+rWaWOHirL7P0mrmQOyMVRRuhDpUMSR8K5bdbp5XU=,tag:I8xvI4xOeePlROotZ4+uTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T03:39:21Z"
    mac: ENC[AES256_GCM,data:EHTydpCiuzgGCzrUEjyD/X8dDAqb6Zrg2+4pUlGh6gdPdmBB6xIE2YY0dhSNjizxa4n0kcMSXXpWKcLlF4lJeGH3B5z3A5vcuxMMUdAfu7wL+pck3bAOOBLHj41Rp+YhugZsE6Ym6iThZPIDbFgf3Inp67O5XoQ9bCInzFsC15k=,iv:NDC7CAMqD9zNd74m3k1NcpkmiNyDd+4VNP+XJdYG79Q=,tag:E8hu7qUIaSS7puhAatTCYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
