# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: openmu
stringData:
  DB_HOST: ENC[AES256_GCM,data:V3N7+Fg5Y15QG1rbCaddvEHfA3NcO3E6QUs+iks+9R0eAkWA4r4=,iv:Nbg0LszPhGLTiFN8//ypq1NsGoFrDVyzFUklY7JqxwU=,tag:FD6i9droZqFsIq37QkqZLQ==,type:str]
  DB_ADMIN_USER: ENC[AES256_GCM,data:AB+gKVlztcg=,iv:WfErnnnASxlVUFsNx1lYUfeHEwp2gTPR4c1hSF4ifr8=,tag:GfhbqgZMk2Df6tGYn70HOA==,type:str]
  DB_ADMIN_PW: ENC[AES256_GCM,data:WsdecdTMReUIeopgah2KCQ==,iv:fY4Wu3Vj6rNSz+e7Z5a27ojSSJjuqTpJGSQZqv4MYbY=,tag:oE0deZxnyMqR/10FjH6jxg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
        MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
        dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
        eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
        ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-01-18T06:13:07Z"
  mac: ENC[AES256_GCM,data:SnAWj4ltglgZ69m5pys1ROsVaY0aGC6G/Z/8H5poyg4+HJdlE3xRATrJSNcbha8WhRDhnsBgR8h47Qm3upbkqhL82FLR/gPrzAH5mmGQ2/qf3ONHU1owtbr+K+jixcIpsPCbvHo3YJ6r/5FNZvqkYJPTk7N4fz9gZmbq5t9/Wiw=,iv:mLuIkdtZsSYFxW+wDpPAoGktQpHjnOqDY/i1VL7k3rQ=,tag:3yEFY8Wre9iFgi+zexFvsQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
