# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: automation
stringData:
    DB_HOST: ENC[AES256_GCM,data:V3N7+Fg5Y15QG1rbCaddvEHfA3NcO3E6QUs+iks+9R0eAkWA4r4=,iv:Nbg0LszPhGLTiFN8//ypq1NsGoFrDVyzFUklY7JqxwU=,tag:FD6i9droZqFsIq37QkqZLQ==,type:str]
    DB_ADMIN_USER: ENC[AES256_GCM,data:klEo+isQ,iv:IIeFQdhdO3+5zoAbulOckXlwdgAa5cnHJoDZRh6+TrY=,tag:5RhBtybSGzBmRYacy3nWjA==,type:str]
    DB_ADMIN_PW: ENC[AES256_GCM,data:nNUkOFEmWoxK6mq1k0U=,iv:fxx72nUc/JuGUicDkCmyzNez1wng9tHouLmBUyBk+lk=,tag:xi+qbBNKpyX1J3Xy2Pp4FQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-18T06:00:38Z"
    mac: ENC[AES256_GCM,data:tywQvHFJtc0/pTE6FOzA2dR5cbXGSg0ruUKoXSgJ+6/aXNklGgEErcS9ah4dRzefJGIA3E+s+6fsWqaeu/0khB3F4nWcGKzCXCpEdEtUMTg0Zur1Za2Vi2T+PwIrI0EBnnNzS9ELPE9gIMhwYtmFf78u4RtbBxlvvPRQk+rty6k=,iv:8qodB+rIkCBet+Qb7kjZYX+VWTHw1MxGhPSHXpIctn8=,tag:2ZxCEukJhudpitbxwaaoqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
