---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app rathole-server
  namespace: tunnel
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          secret.reloader.stakater.com/reload: "rathole-server-secrets"
        containers:
          main:
            image:
              repository: rapiz1/rathole
              tag: v0.5.0
              pullPolicy: Always
            args:
              - --server
              - /app/server.toml
            # resources:
            #   requests:
            #     cpu: 250m
            #     memory: 256Mi
            #   limits:
            #     cpu: 500m
            #     memory: 512Mi

    service:
      main:
        controller: main
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.0.99.212
        ports:
          http:
            port: 2334
          mitm:
            port: 5202

    ingress:
      mitm:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          nginx.ingress.kubernetes.io/enable-cors: "true"
          nginx.ingress.kubernetes.io/cors-allow-origin: "*"
        hosts:
          - host: &host "mitm-proxy.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: mitm
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: secret
        name: "rathole-server-secrets"
        globalMounts:
          - path: /app/server.toml
            subPath: server.toml
