apiVersion: v1
kind: ConfigMap
metadata:
  name: dapr-components-config
  namespace: openmu-prod
data:
  config.yaml: |-
    apiVersion: dapr.io/v1alpha1
    kind: Configuration
    metadata:
      name: daprConfig
      namespace: default
    spec:
      tracing:
        enabled: true
        samplingRate: "1"
        zipkin:
          endpointAddress: "http://zipkin.openmu-prod.svc.cluster.local:9411/api/v2/spans"
  localSecretStore.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: secrets
      namespace: default
    spec:
      type: secretstores.local.file
      version: v1
      metadata:
      - name: secretsFile
        value: components/secrets.json
      - name: nestedSeparator
        value: ":"
  login-state.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: login-state
    spec:
      spec:
      type: state.redis
      version: v1
      metadata:
      - name: redisHost
        value: redis.database.svc.cluster.local:6379
      #- name: ttlInSeconds
      #  value: <int> # Optional
  pubsub.yaml: |
    apiVersion: dapr.io/v1alpha1
    kind: Component
    metadata:
      name: pubsub
    spec:
      type: pubsub.rabbitmq
      version: v1
      metadata:
      - name: host
        value: "amqp://pubsub.openmu-prod.svc.cluster.local:5672"
      - name: durable
        value: "true"
      - name: deletedWhenUnused
        value: "false"
      - name: autoAck
        value: "false"
      - name: reconnectWait
        value: "0"
      - name: concurrency
        value: parallel
