---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
  namespace: openmu-prod
spec:
  tracing:
    enabled: true
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.openmu-prod.svc.cluster.local:9411/api/v2/spans"
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secrets
  namespace: openmu-prod
spec:
  type: secretstores.kubernetes
  version: v1
  metadata:
    - defaultNamespace: openmu-prod
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: login-state
  namespace: openmu-prod
spec:
  spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: redis.database.svc.cluster.local:6379
    #- name: ttlInSeconds
    #  value: <int> # Optional
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: openmu-prod
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: host
      value: "amqp://pubsub.openmu-prod.svc.cluster.local:5672"
    - name: durable
      value: "true"
    - name: deletedWhenUnused
      value: "false"
    - name: autoAck
      value: "false"
    - name: reconnectWait
      value: "0"
    - name: concurrency
      value: parallel
