# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: openmu-prod
stringData:
    DB_HOST: ENC[AES256_GCM,data:LIKKD+p5ucq8KuLVLuz9Aw0dFj5y2KC7blYn48tMwUouLpRoAiszT1gep3cP,iv:8HvLFUWmPgnOb+Bqa8IWih9VmUhOraceqsritQbx14c=,tag:o1wzXWB5RWsDLZrU1YDsYA==,type:str]
    DB_ADMIN_USER: ENC[AES256_GCM,data:AB+gKVlztcg=,iv:WfErnnnASxlVUFsNx1lYUfeHEwp2gTPR4c1hSF4ifr8=,tag:GfhbqgZMk2Df6tGYn70HOA==,type:str]
    DB_ADMIN_PW: ENC[AES256_GCM,data:7dbQZR7UFS1wT8nZDx4=,iv:DAeF9ktjwlwNpdeXWO4zJtC6IL3lqwFyKh9CwRZSlvY=,tag:aFQ2EBgN0oI0t59/w6059Q==,type:str]
    dapr-secrets.json: ENC[AES256_GCM,data:oWCRXYBquKJHD0YTaY/cGIPSvFjltJE8M/NW6meSK3vw2zd1AOHLP5qn046ckXI7fHeU+6nUjeBdWw2plnZEdaVKOgCSIOanPqnDbcd/Xdt1AA/POs/4Ic3QcC4Li4MRTltxFe4iA6nEP0BALpfD5O2MpdCRdUKd17f/2CaN7fUToMWxNPBLrtXx841UOHW/v3wvuv07EiwWK4hX78uW+jqN8+9VylfZzMDWjl3Ch61YLUwfF8MZ6sHdApSmcNvJzv70JJl4vpmbXyXx82Bmrd+Y3kNhDf+UezlU8oMbAj79V/G4CYi/B42RsAYQSCxEKterPtNVI3clD36iLpzB9QY8ueDPIiCdkt00SG8QT2ZCqKWpGJLbMxSHdlRcLueU29wWUYcCDUa7uVgUh+czuxJhf/2fZBj0PhCcbx5BgJYPabE9wK6BNYlkwnrkTpOkiHJcAxp2Fn6juXkrLn4XGbOkvq6Nciqcu0w0NEsMhByyp5j97YARHHvdYDsriC8Xd9lgvh9S7LgF5toFBzgdUGjkXkFuzJhbEBAJECM2zCe1KBcEvibE1a/PrqXhcaxMXx0BiO+Xxl90Ig+hcCI4oi6DSuElM0E3qqApJ1Kj/gJwLaELhzxjnpKX41AmVMCWnpVJ59ZCbF90ZoCmaGz5eFmhDoMvsfK1wtvB0RNHRL0IBoOlXJH6Ynv+alA7+ODIFYPzS37eF9cQpulj2g8BqeMA0zIcWsFYzxAbsbacw6vClDhHfY8ajAUqY+MlWB9av+Ssa/r0F6WtA1P5A7Ed6fApFHt9FKozKl7p52kiH1ODj/yW7EKB7GAocAvdwwTLWTGvd0NZkgwZgiZE0D5Ij9PhPUxVBMZ9kT9+tvAssXAA+MFJTL/lOtTbl6ApqX67txe3JyhKeaueDrSBSZ0Fuzq6Ta9s1+y5ghvdnmZHpW7D3j3eYT1TFcLYAKmsQrmWXaLpdkMzx70xIHiO0ICLK3/pDwcbvP91oMXZK/WJo0wwcHKlOvkys583SwiLBDvpC4xDGzJrKXQLAMDRoMAqDN8W59RvxCZYailUDo3KF3Z7KbP4p2/P0mmwN9q8mRRwsR76ZEPbCQTxPdE6dZXhkyW+BukyDil8fYigrq6/Q5Epauu40hG8uuGThcAny0qKv0KBMAcMC8IERVKWCD0dwIGUS05oQu5c+hS/91qgniqJ5U4YWjgXHcz8xevfllyDe5GNLHWVf5+pqkXSvRJ7KxLaiy2ox0ryR+Dz/20CYklYWljnONRDZfA/u27q5hUNqeTguQVWlHwm2DgrsSdeTY1i7iE58/TRmPOh9x6DhjSAjl7XXa7ay71p07IHKnuyO1rE08njxjsQ4ITJy/dF5F+8Mk7eFfAOagqE84+sbWSDT+agKLmF+oxJ5CyUNm3vT5QwQHwOvFLLmzNhWadNtDEuqm3btxvMjl6OJjzuQDTu4sLfxWXfCoTC+YRPWxejVJYjZPjjlZekiuY4gTFL0Z4FhmbE9s/xsWqQ0A/U/P/Jh3OCmFYFIGkoLYoh28+F8JRUVraYhRwmJwHdwKOqEi6uw/hRt+GqiKw7vnrmAIelI1KvbSmKOT5IXf1Zk7fSJtYMwo+NJgoPe2X6Jwu/axrx3PoP4FYNfBaurHeYq2Pf2PHD33TlN/eyigAgx2h0I7m5/JzguvlyitM8YkMrtDh+nSvmwRKiqLDw696XiO48F4bT8EU+8PSjsVPcjA2vDjb5rjk7jUihe4v+X+xcNDhZff7kQwG4bhfThRaHY1mGQX3smjtqLma9wmiUwyg9FuIAajxwHs1p7zYB4UDOjfV7OkrE/0UHQA0vuchyg5zYEQBh2ZvsSVbqmqy7BXBZ+TxrSj7rtVAzuTWGP1aDHu/LBgkxsG09TFVCShCX3y+/PHFAJq7mAkAEbsJDZSZ/tVJgotvVVrrJOHgdVZpxmEVLXzxtsD1ZtQ==,iv:kPH6YVmy7OzdRntsSfy0Kg0BvkeEcFG626YqrX+dISc=,tag:rH2R11Vxc2edb9ayybdnbA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T00:15:28Z"
    mac: ENC[AES256_GCM,data:FpD9zjiQhiWLJpqknBegJEr1FPYwlBcXOpD88JthjYIm1sqfC2MbAfvOAqcK26goVJEcd2n2UGsDrifXQbzUQnSwWVHkzaNfepw7Em8gDEdbFIr0HkkmmBbSCkiAaLjSLIy2BH1ok/foZjWuizkLAaMl7pLi8HzyIb69ZyATPbI=,iv:ougbo2bdI/YCgkgUa0KD6XrZdgS5t8Dwg556Blpm3Oo=,tag:GjSe9IVY45dsFls0Bl3BDQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
