# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: connection-strings
    namespace: openmu-prod
stringData:
    MUnique.OpenMU.Persistence.EntityFramework.EntityDataContext: ENC[AES256_GCM,data:6L40p5MiqYdmdtBW/WLiJgttfM522isjKvH6mhn2XJTCCZHpyvcCeSRZqe2gHbZYTK9vdoqhUNqCfqjJdX+4OPeEp6I2x5OeEyWzW7xuE/jV+pyNiuW52ra8f2+0Qfy/flrsnTZ+PRxZ9jhRAAKsvV13rrt8hQLbmTgYrFKJNZ1EQ7s=,iv:kEa12BLt7VG5VecZ1wIdvhhN4mY0UPc5u80WvjR3UpQ=,tag:66SDFdqKD7MSd9yvKXEwBA==,type:str]
    DB_HOST: ENC[AES256_GCM,data:LIKKD+p5ucq8KuLVLuz9Aw0dFj5y2KC7blYn48tMwUouLpRoAiszT1gep3cP,iv:8HvLFUWmPgnOb+Bqa8IWih9VmUhOraceqsritQbx14c=,tag:o1wzXWB5RWsDLZrU1YDsYA==,type:str]
    DB_ADMIN_USER: ENC[AES256_GCM,data:AB+gKVlztcg=,iv:WfErnnnASxlVUFsNx1lYUfeHEwp2gTPR4c1hSF4ifr8=,tag:GfhbqgZMk2Df6tGYn70HOA==,type:str]
    DB_ADMIN_PW: ENC[AES256_GCM,data:7dbQZR7UFS1wT8nZDx4=,iv:DAeF9ktjwlwNpdeXWO4zJtC6IL3lqwFyKh9CwRZSlvY=,tag:aFQ2EBgN0oI0t59/w6059Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-21T14:47:21Z"
    mac: ENC[AES256_GCM,data:bSV/ByVHfRCnTj8b5WV60UhfuHDboP6zTZtwOE8r0zKQOv3Q9HsAxmzpqrNYj9FOJmRpRBsIs4YICmZvkKMXbD9iiJEOlG4NS7VTkELgqyrKxnffsmHJeHJinKiTCeClHMK2yrDXogy4Nz1PIeMjFvEt80fbqnXic8sgHOX1WaI=,iv:TSOqN9d78v1rHEcsO4HWI3RRLai3UXubtFhWpv6z+3U=,tag:EHTtlZ3+37ccx6ciD3MSgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
