# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: openmu-prod
stringData:
    DB_HOST: ENC[AES256_GCM,data:V3N7+Fg5Y15QG1rbCaddvEHfA3NcO3E6QUs+iks+9R0eAkWA4r4=,iv:Nbg0LszPhGLTiFN8//ypq1NsGoFrDVyzFUklY7JqxwU=,tag:FD6i9droZqFsIq37QkqZLQ==,type:str]
    DB_ADMIN_USER: ENC[AES256_GCM,data:AB+gKVlztcg=,iv:WfErnnnASxlVUFsNx1lYUfeHEwp2gTPR4c1hSF4ifr8=,tag:GfhbqgZMk2Df6tGYn70HOA==,type:str]
    DB_ADMIN_PW: ENC[AES256_GCM,data:WsdecdTMReUIeopgah2KCQ==,iv:fY4Wu3Vj6rNSz+e7Z5a27ojSSJjuqTpJGSQZqv4MYbY=,tag:oE0deZxnyMqR/10FjH6jxg==,type:str]
    dapr-secrets.json: ENC[AES256_GCM,data:910eAXSC7MYVFcSXcY/ZwfpjmznUNWJUFX4j0H7sJ1wlkYCSVKpJ9K/28uIXvF3uU2WMEM06IVAfMCQkR/6Vlmg0MTr4zieykcmR8yZgFwl1s0W1ThGOOHKngFPKHgboF8CZK2FkNckRmAxhnB2FM54IE5eA092U1oN3ePg0lwe8Xvs/5poUbyoI88zG7aAA8B8sFVWZ6+4NNwCyFelX9Z8yRFWyr0isGizm8V3hRzWzG5eYkveICZotB3QQaarWDE7tOBdlDMwDjELfkj7LuA8iSH3eQjUIYMvflgBdziPar6jIXRqobtHYCc8454A9PGPfAJwuyqALNI7q3MmA8aqyOXPSME16HeU5f4LqffrGFHnenyO3eAnUnyGLUOVtKkejcbxCIM1yOOZCBXBoT/ybFxlD7u79G1PDavukigUMWiDD4UUFLwK7Ogmmr5UZgn2Rs0jucS8vFKMW5SjUVnVigT7a58G9WxljyLHjxS8cfpajSuyWGGSF64SHmO9U9UFsIWFPFXntC3ldXKJ8g9SAyQkleX4jzHHhruCkco/J8iAGv/xH3AsI7Se46T0G4qamkgokiLfk0qpAxxuk7x4h15550CnVPp/wZxsa6N8E6BbXF5KV0yr9g57VUqA0iYE1JpYn4J/1U8YrJUybn7usUxcz6gfbPWZaBVdgOQ3DKX3IXP/GLed7+/YmsJ0NFtCvvfqH/oh95V8F2B2lKSWNl9nsqlWrW2oyrorxwwxaTKd0tdw8m7oZrKHGPJ5EZAVMH8zOpWqbHkrPe68cJc/MeCoM5k/bEe89V4D8iMsd3n7FMge4pRndbjgVWfmMKzw4I4HYwghzvj1vQxBRqpDKI0wwgTAH94raUExAmOUM23KBxpzkk9kJqBDQa7+BQQVsY4vd5alL2tJGauFIVrR3cqNW1guzUUEMKAlCSwX5DRYizUYsla4A1FqyDRa0woAitpRgt8cb9X9/EUjN6KuPjmrH4bTP+smSv5u8usO+05TjQ4cazs4S66/iCMUZjIUODK+jZX9bZwMQBgKB1nD3bXuIL5dkYkfUQbnJTUeHCTm06qvilK/nNbrgVztuMCG++x2EqzxTbWZ3IXFNL57R2fcpecjFpvFid11aC1Tg6gERdwavcntxM9aAS5R9IitqZX6qlSqMnF7mAPhpmAGstPnlGwbnLzSlN8y/q7BwBHM43MwT6n1Xidee/WTbEjHbYWES1ze1Ih/fmmuRqiUBKBweCRLh+gtBFbPMblFNmrBagIAwDsLyEHukimOup5v27q1XsnUUX6c81f5wLJSoTsCejtu79lWuIZAPkbUEus4t+5knZ11XtJhw4ft96EvxMQSIIJY81RvKUYdh6VmQeYNMaZdKFO97FE5Ytf6KUWMlYJ5E9V3L45V02mFysGRqr5pGtzpjXD/qqGDPl5nH0XvK0z+lFkFhsF5WNxwlXeU7/xnPue3sTsdGFPRKS1jWcIKDY5l8xvue5moVLieX85NJtEQykMGAB28cZjDNpFCi8yxJ7MhPs5l7/7FWfs/b5HtrfuW4UsO/2zDDEo/Hd/SiJ+Rwu8l2FKdankf0yMvdHrYhHXZW5LQEa1l5ToDchjh1,iv:6aceU5ba5Qye8zEzGUpjFA7CzEOR9MgQs/D4I72MuSM=,tag:bc+NfVlG8+QXJMZ1OzOh4g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T16:29:35Z"
    mac: ENC[AES256_GCM,data:5E1H570XdeHKahRkMnpvYqoazZrWdXvgZgieKShVKrGW4JZtdxbvWjDpJYAhdmTkhN//DcatAqSRNu4gaLhTpQrBiMb7QpDl8CbKpvIOIbrzDJfKERotYEgrQ2f300WIw6KYCVrQ3j8/A4K/2A8RnIpFfCATfjA5rHQIm6TpVB4=,iv:quMYYRQppAz9wSG9VBIDL1BZjqaQ+8FWtHXHCBtANmo=,tag:KpFb7U0Qs9crlNhn/m2FrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
