# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: connection-strings
    namespace: openmu-prod
stringData:
    MUnique.OpenMU.Persistence.EntityFramework.EntityDataContext: ENC[AES256_GCM,data:dOMsR7fYcm13N1XWtbNePxH0MHsknxGIqyuXNJADTZlfoa0+oLjEJUT1MuWT2Oh5F0YeRpIxKU+mx9XDJmnBZB2O+36J/ODTY7sEdoi2UnSgE4mrBi8v+7F2sHyAxeKVVyt1Qw+1oDtv19PQ3gfal+D/7kznCDlLZOyN1TYV5lL9afx6Sw+/uzkTuJ0=,iv:0Xsz5QgkF8h8de+zHU5xfz8BAjbJDxpvQ7cb19aCY6s=,tag:PWYuFOuCikiezP+IBH6ykQ==,type:str]
    MUnique.OpenMU.Persistence.EntityFramework.TypedContext`1: ENC[AES256_GCM,data:/p1V6JLs4da4SStsmomhEMhnfMZo8iEkS2h5DNg95YkFhqXWpspX2F+GsNmf0PZH0V9mesvuW91QQ7Syp4mc+jokfCPRGJh9lFadTVcoCU6XXM1X1zRtBM7v/SGXlpRBaCopssaP6f0t3FVJZQ4oGYj8kOzUPKhru6rnKRDq/WpjpFXnE2SBmkzzDZs=,iv:6Sq3E97YvdRXP9t4Onm3c3Uolpe8I1uGToo/+Qwpzcg=,tag:LbFWo/ffNpsxoM7QXK5F7w==,type:str]
    MUnique.OpenMU.Persistence.EntityFramework.ConfigurationContext: ENC[AES256_GCM,data:kH0ZeHAB9UKG8gqrnOCr2DbmC8CmrCHci2W6IxFxmnvJDXEyvhvZzSo2ESR2eDTssKfW/CYmBgdYVADzIQbT9Eh8ohi6EPSseFoLfjARts7fZJmic7iddZNDl+Mewl+CwBT1clR/pVcO+Uf/UwIVLXzHgV8IfXg+GnttLOIOvGzS2RsXVHahgnj8,iv:rKtLI/4knxxkug8A2x5xAXfypLkQNcG5mLIJO+W2BDs=,tag:qGojdlTYmn+nW9ZwhWbH2Q==,type:str]
    MUnique.OpenMU.Persistence.EntityFramework.AccountContext: ENC[AES256_GCM,data:KVIaqu/YmAU721IhiB2OCl2XYy4DXyRIhX6xNW/6UdDJiXAbLUqVDlDP7pKfi87e114iDgl1sx5Uo6vSUOX065zNM8uM9Jd1sraaI7PQu1Hp4/pkb+x8oS2Nm2sxci1xGt6TEp/glbVxm0W4m4IjJo78GVEq3ZcZ9gli7wJwvXpvmo44yCKjqOJMoQ==,iv:DwLCNHTfKFNlRlYPykV7ftePtq5Cpfza5F5oJLISrdY=,tag:eIliuepx993L3ap53duWVQ==,type:str]
    MUnique.OpenMU.Persistence.EntityFramework.TradeContext: ENC[AES256_GCM,data:tRobrVi+BNmjAFKDlw2/EYHMwMKIgD6V60LKHDlvIkNIDzdgSlY54ySUHzdHFj14XnSDyfdzR1oS4aNv2AG2qGu3B8ADv/hf/3+WwEn22YbXVhpMq/A7FR9ZXEyuujaaDJQEWPKEqqldW1/y1vx4FoYsuPvhirApWYK8PiQNqIb7iOdNz7TP7KlVGg==,iv:Hdgh3g3pyFGDBk4UWjBEW5pN/FNOTPXpblIa6lRsCkw=,tag:CoX9iEiM9K0Fb7pkARONPA==,type:str]
    MUnique.OpenMU.Persistence.EntityFramework.FriendContext: ENC[AES256_GCM,data:P5Jq2AqmX8E2/PX4sF7JCJqOptvaK3+HeE/HB6h3jVI7A2u99SQ0jEuALrPYF3ah9muA7/svRTfK+lTLjr5mbcpwbwvdPpSrusYFs7AmWz48CDF9Rj0kiS/xeaT47b2da4SYSKW3giff8tYsu5JQLbU4U+YjZe+Hhn+s2+BMsz1i5a25AirazbP7,iv:/e6S8Rtm174UdZfzJN9hFshI3By1YAS2fe+IRb3kD0w=,tag:IYgueuMoEOTa+pEhlplaZQ==,type:str]
    MUnique.OpenMU.Persistence.EntityFramework.GuildContext: ENC[AES256_GCM,data:GA6lZir+07qCS+aYBVpv+Wurs1JMBdTokN0X1fbHUFhO7wSBkhLu4zTJ3pvYkSG21y3cJvM0GqLCG/vLTAo5rP20aQGGNC0nAc2wGHsYqDlEcmlSSvelf2c7ts87QDIUzA4wObB5bwpo3zYApdBRF09pI/lq7dx1TlUV5IFqbvI8J9ZNsAQJ+5k=,iv:3urzT8Zi+mRo4ntFqpwqYZD7T0MZ7NK5PnSKgbPXMrw=,tag:uVLyW/83WEsP9Xqo3c8qDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-22T09:18:50Z"
    mac: ENC[AES256_GCM,data:ckQ0P3pxksWozEnLSQ0bm9jf8AnFfdmQ2BgFS5DZ2lx67iLS8l3J3txcLNvGtndTJifUtK7+OGcSw+tVHJPrRYz9t1ipTbz/sWanDWBhC0qADqn5FrEVBMglgoK6BMlD1FAJolJCok2wLM4BtC+uKBtBadXz6pTjTRvachMilIg=,iv:RHbOSfIXrBicVQgwZ+DDPXKa3KmYw3T7KriK8hI/Sgo=,tag:4c43hcUfqiOTD/ZkOGew5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
