---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-machine-learning-cache
  namespace: immich
  labels:
    app.kubernetes.io/name: &name immich-machine-learning
    app.kubernetes.io/instance: *name
spec:
  storageClassName: home-cluster-nfs-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
