---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-elasticsearch-staging
  namespace: flux-system
spec:
  targetNamespace: database
  path: ./kubernetes/apps/database/elasticsearch/staging/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
