# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: comabase
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:tutFMWLsfctdU7HUsmXvItVJ,iv:y3OgwG8LDcZ46us0tsGy0ruC8O3f2KhAJSmTMcmrSok=,tag:q0/wzq2e6eqr+Jbh3iWYCw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ZwSNyiZpwyV6Vq7z6UQ1N7ApNrsDwV8hFfkkpNjv3gK802gIcGU=,iv:kXxEJik6d0Dn7yYOWzsuTsSEpDqA8aA5RiyX5Fxjbzs=,tag:GB8hpgGf5x8bm8ky1OWnYQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:BUunwCtLWRUSwHHaEjrQ/u5J,iv:tt2s1+fzgwZOQzCBm/GgzFJ+qeU+eAsJkmO04A5Gq1A=,tag:HkiPl1YMga/uZ56nU4Mniw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:0he9/myTgQ/aimZsS+o=,iv:0Ny9xtahupJ49xZWtFGCBGEaXvsjuDPHuvMgdOu2XL4=,tag:eun/CmlKv6Mab0agKxOAAQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:VL2Mif7ldc2JDLUFfwJHCw==,iv:84FaQeN+6rL8t2a0pJ9L3zPpjuko621FIPSa9LBhRTI=,tag:PnfYdPdUdZ0Z0QmZ6MFskw==,type:str]
    redis-password: ENC[AES256_GCM,data:WoETu6fjenh7hEg+St8=,iv:SqZmVqiHn33a9KeXbKPLV+DP8cld/n2KVDe1TouMY00=,tag:+rbBbGDHaO8yG3rTQMU9pw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T23:51:06Z"
    mac: ENC[AES256_GCM,data:SGYqaBTRJth8AbkkfvNtfWPyhfCzIoept4ByqFLvSmbeh2giI7op/8RIh5gXQ9pGQptvxfL/DtT3JEmaIfMs3bAhj/J2bFsvj1ue16KDUuahSqsOGQFZUKT4clDnM4300Xl5nogwz9FWd7e3mMnZ8MX4RG+DrCJvW/9egmAWqGo=,iv:I30HzHO0Y0/v0Zw9G8fS2p+bQC5Kmn2rLFBZAW+oKEo=,tag:DzIFd+yZPFTuVK9lw+vvvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
