{
 "title": "Sms Gateways",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Company SMS Banking",
   "type": "logs",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{device=\"475_sms_banking\"} |= ``"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "esp_uptime{job=\"sms_gateway\", instance=\"esp32_475\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heartbeat{job=\"sms_gateway\", instance=\"esp32_475\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "esp_free_heap{job=\"sms_gateway\", instance=\"esp32_475\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}