---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: home-cluster-camera-nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.99.166
  share: /mnt/camera_data
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
