---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mcluster-nfs-1
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.99.111
  share: /srv/nfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
