# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: paperless-ai-env-secrets
stringData:
    PAPERLESS_API_URL: ENC[AES256_GCM,data:IKns32Za/8mK9Ir9pqUju/EJv5NIZfrwPAeT18OQH+fG,iv:Tyz2Mn5OjcIBAuvhGJfd22YvummBkNQBH7boDy4wo+g=,tag:7gaepvwNqMY/sbBxZZsI/w==,type:str]
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:rOWnZCBYqXJlpmmi+ze7dr/m2tLaURVfaibGJ66242Xt7bgXCrArlw==,iv:27vDxxPPeDvQNE3CqWkxQgt1jIRdMq2j4bn1PjDr5Io=,tag:lBEDj7ZqMDtaWAsguqdLYg==,type:str]
    PAPERLESS_USERNAME: ENC[AES256_GCM,data:I+MgPeXGKYA=,iv:2baJUI9qZWu+vb/6wpPEVI6eyKM9MZrWvoTY+mo4HDQ=,tag:XK2jHH0Itnkm1gssMMoBEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T03:22:24Z"
    mac: ENC[AES256_GCM,data:m1QC4EfRK5+G5QOWqpMM470+h3s+NvL7SK5EYhk/L8EBGfNZFyhsMIpXSqtC/hWo76a1ES63WtfvA5VMutz2+Kb1nf2Y/T5LwDVmio7oBH7iBhJhI+CLNycerPw6Q2S2UIqOiV2NoeW2JliJsXjvZ+84G0wiCEvf91Vsu+jW+Hw=,iv:fCSQxeyYtitUf93SffH9AC+AVzlIgwwNdOgceWK29dI=,tag:f/y3kXUDO8VvFBbpmc6D7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
