# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: flowise
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:wRWZ9kyyiA==,iv:9vuas6zdD4Kl562XvZFmBm1DcuLmcfHuYGvm5tBpa8g=,tag:RdthVHv2E1eo9OJegLU/FA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:P3Ozsqt2r/nGl1r5aItQmXqMaDwN7RbhSeDVM0U/BOWUHWWp6dg=,iv:rxXA0BRy4cLY1fyOK2+aDX3rKDx6Ce5T/wRdkwzwmT8=,tag:Qr6mPnXvsytjJKDRYbdz4Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:e/TjrHxqCg==,iv:it04vE1neEQ+t4Nn8vITbonkuidmaR/VAqRCNNZBOTw=,tag:QfdetNlH6AbX6hG7sj97Mw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:eOAzn+A+MpEMbugI2HrdIw==,iv:0o8oikbvMYg+xmy+mqb8ATPArbuPtz578gbYecFvRcY=,tag:NA0lsm7WntDv2s/+frNimA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:a3a9Zqlg0LE//DJym7oIyw==,iv:8sEQwAcO28XcwVTslKeDFtYCZaf3Ysyh8EChEDU+utM=,tag:A5mTFnCMwkO2Uv7lGY5XdQ==,type:str]
    flowise.username: ENC[AES256_GCM,data:hVjFsg==,iv:BzHnqTStxjFQ526bvrK+iaMRv2NCJQ/w1ljuvQ32iZA=,tag:/XN13Sn5rRvbij/iylHX1A==,type:str]
    flowise.password: ENC[AES256_GCM,data:ZrgHyauy1KEI0fLVxME=,iv:MzlR8rMRjml7aoF9P422BDxLIKArg8g4fgF1ab7aZcU=,tag:QCgC1TuRwgTwXTuP8/Lmww==,type:str]
    flowise.secretkey.overwrite: ENC[AES256_GCM,data:Y0P4Hgx+wwttPYQ/ROLduUU512RnaXjAFd2sw/d47Mc=,iv:o4ylyQ/QxGE8eqGn1sXJoy61Ft3eQeyvydb/3whkCKE=,tag:h7iqT0JU46Cniyo/3UvX/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-08T04:32:03Z"
    mac: ENC[AES256_GCM,data:7osX1mv9GnNBbO9tWprNdIOZuXLnU07FoR6lVes7Nb4gIW/wdxHfAHPZxQrIFLtmd5S1544NWUHeGtsA4WLy7z6YbgfLNPfVgXVOkIJf4oeo+H3ma9xqCYN9l9s1wMjnhd7FnHeLiYwcM0DsTP3pP87Wzo8nPkfnmkNn6HIq1bo=,iv:IHKTBOMoM1V38Uw88yUh69l3pj8iuO1lKhqzEQDdng4=,tag:BveJNcZoN+pLv7gDOdjMFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
