# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
    namespace: zigbee2mqtt
stringData:
    #ENC[AES256_GCM,data:Zic6bA==,iv:R0jvj0mn2/cPrPzJjjXw/Q35Iq0PcXvgVVYWazOY51A=,tag:owl/hKdOC64sBcg9+Xb7Xg==,type:comment]
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:eh1FBGqLd/2UqknpoQZaqQqaYh1qP6o+0Yh08bhL9pE=,iv:+eOHN2VmBbfRZFrZNrebIutmzIrp7jAA5nXjpNu7tdw=,tag:ytPeaX1RJkV6U5MmVro86g==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:aMMp5jI=,iv:8YI2x6Hy9ot7OVodVHzkSWh8OMVu3QxI/D2GKg6Qef4=,tag:i3+efaRG/kDCNRkO5qKP5g==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:c0Hmd646xv/JACy9qPlRUWdvpaA4qgOWcHHx+udZkei0qEMx8hsCK9/cuL5OlEnC6Qf+VtCmP1on+eSktS4PF0O4CMlb78Q=,iv:4c5/J8VUziyhYyNxYW81JzB/H9nYarVJDYF4OD1VmvU=,tag:Fdebu+riA/uNOxEsSo4jtg==,type:str]
    #ENC[AES256_GCM,data:QANgkH16+JaNAw==,iv:RNzBajwP9allEhmX76S1dC0fFoa/ZMnJibvgnOiyOkU=,tag:ZRhTIF0OxqrEgiaPWlBvug==,type:comment]
    ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:4+R8MQ==,iv:yqmcqVgjvqNih+sQz6iv5OGNM6ioWQNPj09Quyx+W2U=,tag:qCSyHEOFr3oRIEG4kRNPAA==,type:str]
    ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:Vl0kuMgX9cbXSpKTFKjQRg==,iv:oXN2t/dWUGIuYgAWHQk0zZ9wljVeZyjbhUUheXNI1ac=,tag:CxoUMLMc7eHadOMvlNWdng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-08T06:51:40Z"
    mac: ENC[AES256_GCM,data:/zeBY+4R7Dd6Cj+amwPhp7nrblD6BYiESABRz7mLCT3ocscj0r4Na0ILM8egKgj/dXItQAQiIb8RT9BoprgKg8GE9r0Vc1tmyyFM6VfopntW4mNa/sTdLFAVQSoaEW6kxf+OtWKQRI/NSGEl1zotN8BJTWiiZR671xvGaLTve4c=,iv:wklaN26av2ax9EYYMhPTSDkDIsNH7YLUc6r/9JiEvNM=,tag:JWJ0SPQx2QdVSXTMUzHSjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
