---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-nas-tenant
  namespace: nas-minio
spec:
  interval: 15m
  chart:
    spec:
      chart: tenant
      version: 5.0.11
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    secrets:
      existingSecret:
        name: minio-nas-tenant-env-configuration
    tenant:
      name: nas-minio
      configuration:
        name: minio-nas-tenant-env-configuration
      pools:
        - servers: 1
          name: pool-0
          volumesPerServer: 1
          size: 1000Gi
          storageClassName: nfs-zfs-1
          securityContext:
            runAsUser: 65534
            runAsGroup: 65534
            fsGroup: 65534
            fsGroupChangePolicy: "OnRootMismatch"
            runAsNonRoot: true
          containerSecurityContext:
            runAsUser: 65534
            runAsGroup: 65534
            runAsNonRoot: true
      subPath: /data
      metrics:
        enabled: true
      buckets:
        - name: backups
          objectLock: false
        - name: restic-backups
          objectLock: false
      certificate:
        requestAutoCert: false
        # externalCertSecret:
        #   - name: nas-minio-console-ingress-tls
        #     type: cert-manager.io/v1
    ingress:
      # api:
      #   enabled: false
      #   ingressClassName: internal
      #   # labels: {}
      #   # annotations: {}
      #   # tls:
      #   #   - secretName: nas-minio-ingress-tls
      #   #     hosts:
      #   #       - *host
      #   host: "nas-s3.${SECRET_DOMAIN}"
      #   path: /
      #   pathType: Prefix
      console:
        enabled: true
        ingressClassName: external
        # labels: {}
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        host: &consolehost "console-nas-s3.${SECRET_DOMAIN}"
        tls:
          - secretName: nas-minio-console-ingress-tls
            hosts:
              - *consolehost
        path: /
        pathType: Prefix
