---
kubernetes:
  children:
    master:
      hosts:
        mcluster-master-1:
          ansible_user: mitm
          ansible_host: 10.0.99.201
        mcluster-master-2:
          ansible_user: mitm
          ansible_host: 10.0.99.202
        mcluster-master-3:
          ansible_user: mitm
          ansible_host: 10.0.99.203
    # worker:
    #   hosts:
    #     hc-worker-1:
    #       ansible_user: mitm
    #       ansible_host: 10.0.99.103
