# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vietwings-commerce-env-secrets
stringData:
    DATABASE_TYPE: ENC[AES256_GCM,data:p5llIIDIt7E=,iv:vhcHRrxzsXrFR8QMJgZDNOo9vRQx2rhIzFawWO7mJYE=,tag:WURe8KwFTEZktWPbe4eQHQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ZZxh/jt/gzKVvdiXm2m2Z635CR053NjKqxZfP0zJs4FqRHmDmIqsz2F0umgzy9dsgN1avtdt+0UAYMIo3agQwp/6X2hS1hRbAA5UNHSUaBjslRRUG84ThyKibHHVXgG6ES/LAl8SIhuxy6SQ3Xbduta3gKw1GGP0C1Gy,iv:BNyIt0Kwti1i1LcUPUa4nlb5auhMZPUt0Zz0ovEJ2b4=,tag:iQjgCfSh4ilV7X4zXiYN4Q==,type:str]
    MEDUSA_ADMIN_ONBOARDING_TYPE: ENC[AES256_GCM,data:7KaNSy45QA==,iv:I816J3QIRzBOmnRWEH9QbMVls25UteyxwiITI6Y4Xdo=,tag:QRnk+hyRTT9seZKLQ4Il+A==,type:str]
    STORE_CORS: ENC[AES256_GCM,data:4hVXxiGK8mbXOF9GR1PluBq/5mMzIc7x86AFwXWiq/zW6k6HkmwEfgKTGw==,iv:ln42T7SDnSAHeA85PXMGoR3ib8g94I1jIGLk5vpEm38=,tag:Ac4NCycLVSXI0t86encj0g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-20T15:23:35Z"
    mac: ENC[AES256_GCM,data:pv8TD8ec278+By9vLanQegxCJoQY9EcJF7UqXyfmH9Z4UB5CxEXTbgJDVB7WK2k4GrRk7dPN1Gi/bBXvtLO6V+YvOAS1Y1OOpLHHCnOaBf7uqm2WfFJlp2dy8K1+gSwFA2tyF7Nk5xMs6PWl30t8sHUNxgZTeBMoZsP4mgW+Dx4=,iv:mIJOBlwDJnMEsX13rqWmu6s10rGc351gd6Owxhl2+KQ=,tag:pD0GGda/X8lrXeBHVy8FxQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
