---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app dify-app
  namespace: ai-apps
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        # strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: langgenius/dify-api
              tag: 0.5.2
              pullPolicy: Always
            env:
              MODE: api
            envFrom: &envFrom
              - configMapRef:
                  name: dify-env-configs
              - secretRef:
                  name: dify-env-secrets
            # resources:
            #   requests:
            #     cpu: 200m
            #     memory: 300Mi
            #   limits:
            #     cpu: 2000m
            #     memory: 3000Mi
      worker:
        replicas: 1
        # strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: langgenius/dify-api
              tag: 0.5.2
              pullPolicy: Always
            env:
              MODE: worker
            envFrom: *envFrom
            # resources:
            #   requests:
            #     cpu: 200m
            #     memory: 300Mi
            #   limits:
            #     cpu: 2000m
            #     memory: 3000Mi
      web:
        replicas: 1
        # strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          web:
            image:
              repository: langgenius/dify-web
              tag: 0.5.2
              pullPolicy: Always
            env:
              EDITION: SELF_HOSTED
              # The base URL of console application api server, refers to the Console base URL of WEB service if console domain is
              # different from api or web app domain.
              # example: http://cloud.dify.ai
              CONSOLE_API_URL: "https://dify.${SECRET_DOMAIN}"
              # The URL for Web APP api server, refers to the Web App base URL of WEB service if web app domain is different from
              # console or api domain.
              # example: http://udify.app
              APP_API_URL: "https://dify.${SECRET_DOMAIN}"
              # The DSN for Sentry error reporting. If not set, Sentry error reporting will be disabled.
              SENTRY_DSN: ""
            # resources:
            #   requests:
            #     cpu: 200m
            #     memory: 300Mi
            #   limits:
            #     cpu: 2000m
            #     memory: 3000Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 5001
      web:
        controller: web
        ports:
          http:
            port: 3000

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          # nginx.ingress.kubernetes.io/configuration-snippet: |
          #   rewrite /api/(.*) /$1 break;
          #   set $forwarded_client_ip "";
          #   if ($http_x_forwarded_for ~ "^([^,]+)") {
          #     set $forwarded_client_ip $1;
          #   }
          #   set $client_ip $remote_addr;
          #   if ($forwarded_client_ip != "") {
          #     set $client_ip $forwarded_client_ip;
          #   }
          # nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          # nginx.ingress.kubernetes.io/proxy-body-size: "0"
          # nginx.ingress.kubernetes.io/upstream-hash-by: "$client_ip"
        hosts:
          - host: &host dify.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: web
                  port: http
              - path: /api
                service:
                  name: main
                  port: http
              - path: /v1
                service:
                  name: main
                  port: http
              - path: /files
                service:
                  name: main
                  port: http
              - path: /console/api
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: dify-app
        advancedMounts:
          main:
            main:
              - path: /app/api/storage
          worker:
            main:
              - path: /app/api/storage
