---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../templates/redis
  - ./secret.sops.yaml
  - ./envs-config.yaml
  - ./helm-release.yaml
  # - ../../../../templates/volsync
