---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./cloudnative-pg/ks.yaml
  - ./staging-redis/ks.yaml
  # - ./vitess/ks.yaml
  - ./redis/ks.yaml
  - ./mariadb/ks.yaml
  - ./obsidian-couchdb/ks.yaml
  - ./weaviate/ks.yaml
