---
apiVersion: v1
kind: Namespace
metadata:
  name: business
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: plane
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
