---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.9.1
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    global:
      clusterDomain: "cluster.local"
    gateway:
      enabled: true
    minio:
      enabled: false
    traces:
      otlp:
        http:
          enabled: true
        grpc:
          enabled: true
    distributor:
      config:
        log_received_spans:
          enabled: true
  valuesFrom:
    - name: grafana-tempo-helm-secret-values
      kind: Secret
      valuesKey: values.yaml
