---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-iot-home-assistant-app
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
  path: ./kubernetes/apps/iot/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: home-assistant
      VOLSYNC_CAPACITY: 5Gi
      VOLSYNC_ACCESSMODES: ReadWriteMany
      VOLSYNC_STORAGECLASS: ceph-filesystem
      VOLSYNC_SNAPSHOTCLASS: csi-ceph-filesystem
