# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: home-assistant
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:/OjzdNr9DVzYR2SGSMo=,iv:mZpkyMl3IYcyHUY3tY236aKWWdCO/F48q8m/xP5p+qM=,tag:mIGhApvQkZP3XpT4Iu5CpA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:A5Y8OOgvrhlstqucNpMJsz5oUdpdpstdMya4DCfu98oJSnMvUgY=,iv:mdBVMrTeDPFZpgkLQUs6nsGg3INAQoqEd+wS4r79twE=,tag:VbRtXOkaPX9ZgLsRtlnAcg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:r1vde3SbLrDTVDlKU8s=,iv:aFS8bw7I6X5xXrJwXe3uefflHnOK7B1GiAdGqP7B6+c=,tag:uqweGUAdGYVFzon/v+eM2Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:MZU3ayLrHBOTb6atdx8=,iv:syn1JaEMKlAhcOuFWVJUA1dvkboCgwLUQA0uSVOz0tI=,tag:2n/J2NwmEXignHX74AnWog==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:9Uw6cPLnWqZM6tCEbQ4WgQ==,iv:yvVNLGw8JW/epOqpFI37oJjDAzXRl6WbWIcj1zCl27I=,tag:S3KvMkV3oeeRud9A9PVkNQ==,type:str]
    app.token: ENC[AES256_GCM,data:avELVCytKncl8pUdByMY3rsuVLGREys4rLSSDfRidZk=,iv:3j5l6pJoMuJoOf29BHImkUD9v5hwBMlatl4lO1e9J8Y=,tag:sB2m2WUrHIufM/3s99c+7Q==,type:str]
    app.password: ENC[AES256_GCM,data:IEBippQSObJO0slOAGc=,iv:e+hnyxOFkRGnpnyXTek+qI3dnx0rJqrdUu6xFYE96q0=,tag:kyUmBVpZvVOqghsAwa/YJw==,type:str]
    app.postgres-url: ENC[AES256_GCM,data:6xgSlSCK896WFME6w/agSoUL8M5FKndfhi6cXmBr7Vw6ZkfY3BI+E9acrUJshvf1wmW3d4PbzlV54lMhdYBU5QJO0L1x+6JPlxi6aF+QStVUBYB6xAewHwBGUurQ3nOi0KCeTrkZtR8LHKinW6G/lCDyHQ==,iv:7HO1f5QzdSG/XbIcHvRjU98YLPnGD2/FqXoddqvM5SQ=,tag:WgXDHxrVzMDeSfID1HrJvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-07T23:59:46Z"
    mac: ENC[AES256_GCM,data:U4UofzVc1Kq1CQS4F+wzR0dWqBF15DZXymocQGWU5UKW9cWlyKEbt7swSacjt9e5JTOAW1f0FnmH/kAshG7KM3yJgSDz30AXXXVTO6c4PyHx0Fo6TYZyUhkrMp4wmGYOlH/lVAeXilpPeWCtBz6CG2vQJVdE1mzPETy8vwvYmqA=,iv:lxwrMyhMc9RrpjCKD/KuOO8uknRaLGAMO4KyOC0l7h8=,tag:ZxsBR93mTThdjGedCebGJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
