# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: n8n-app-secrets
    namespace: automation
stringData:
    DB_POSTGRESDB_DATABASE: ENC[AES256_GCM,data:UbJ8,iv:rFbi3VxaBDOMe2PDadF7ZEnLDRhHYe1oAvGFBwR6UCM=,tag:FQmIMmPaiIFlq6ALGE2xdQ==,type:str]
    DB_POSTGRESDB_HOST: ENC[AES256_GCM,data:sbqASEGKdEYy5glGMkCFsJC2UqcXrb9IKZgaTYCxi+TvWmUeY74=,iv:Zh/Il16ElDZ9OacD5/ZWhNL2z5/IKyV5bBJtx7uWG4o=,tag:04jLXKTYIf/PzPA10V7KQw==,type:str]
    DB_POSTGRESDB_USER: ENC[AES256_GCM,data:h2m597H6RXI=,iv:0CnwxyFTr0ar4R34BaimLfB5EC2WvtqJViHuCSBuceo=,tag:vlmWyVae71U+1QNUOOdV0Q==,type:str]
    DB_POSTGRESDB_PASSWORD: ENC[AES256_GCM,data:KNu7j0PBnPVyBMb58hY=,iv:BQVcQI3EPYy9yK+RXwdEb4HYsAkC6cShfvsC5SEvosE=,tag:TWaC1sM0okbH0IxC4v7YIA==,type:str]
    DB_POSTGRESDB_PORT: ENC[AES256_GCM,data:c0NveQ==,iv:5Bkw8UvV85UJo2xtY9BCQyUSHfgJzitj6y3XKB5/rjc=,tag:A2rpTXIMbkKhrcWPWqyV1g==,type:str]
    N8N_ENCRYPTION_KEY: ENC[AES256_GCM,data:/c7ewMRs1nCz5YsQV4TE6ZoSBdNTL7HSrG6LyuWootUY3NB1czOtZzRLsoVl7Wgn+6oCFRccRYxjvcAO6Tweww==,iv:ce28b2Is7Vtx/3wODpFvMYPoKjpWJiCALHaX/EoJbdI=,tag:8NvCVzALMeJtUyq3EqQLzQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-17T04:12:01Z"
    mac: ENC[AES256_GCM,data:KxERF85qUYnHtw7hUTalHroC75FXzxc775ZOMHNyZUeGCxa/5FF8y5Hv+A2rL7SPWfXdLkXouCfvyt6+p0ZoP07e75rwqNJw0uJG75QMd+pAJkaV1z0H/aZYg4D6UCVsBLn9n7GCgUKofer5zrKlghut00Qlug9cVTbGhzJl4y8=,iv:I3hXi9zAfdyKMNfKF5dtijEGkYIxEXw2IoNeVz/ZSi0=,tag:C7w/3IchhrNI79icF3ZEIw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
