---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - ./namespace.yaml
  - ./secrets.sops.yaml
  - ./configmap.yaml
  - ./nfs-pvc.yaml
  - ./server
  - ./machine-learning
