---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
spec:
  storageClassName: nfs-zfs-1
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${SECRET_NFS_ZFS1_SERVER}
    path: /mnt/data/home_cluster_data/immich
  # Note: The first two options are strictly for NFSv4.2
  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
  namespace: immich
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-zfs-1
  resources:
    requests:
      storage: 1Mi # Size does not matter
