# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
stringData:
    #ENC[AES256_GCM,data:GYu+dg==,iv:FY4rBZ0Qt2c5s98Af8mFaEpW4kO0jKd3eHjGr0CTm+w=,tag:DfpJrX36nxlPYCyYFQR4gQ==,type:comment]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:aeLFvImc,iv:3KpwyiXsC7w5jqV5L7Nthsq7ozbs2hDRmYmOLrD0tHU=,tag:7FWCESxvt0iDSiwz7EUf+g==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:Lk30xZVi8J+5joRAKNvFnwrZjlTLDJc8pvzj7s7uk1SSAM6XTDg=,iv:QZn2fFlSKeDA6rj4Jk4NnQkCMDI1r24K5lSqtWy2hus=,tag:GSFyfKFWA1WoLWpajtTbdA==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:/DkJUI0L,iv:pWNkapksTGrawLL9NY8a/klbDxHkbqhJ0cVDFsZWLIY=,tag:TRxHEDWYMwdH1rVzD4ZF3A==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:B0FXcjY3t3WqkCcpqdo=,iv:Mhck+caLKPbrH8SPZWWmr1fak1T0PGyYXYzMYsr29l4=,tag:I85CuwWFr0Ng/187rLYe0w==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:HRVrTLMNyC+Zq8O+NsvZhkjJ+qBFi8IT36opQ1edBQQ=,iv:qHH3L3OVW5BC4fSP1rIR0V6ejbyahIAroGme7YikJQk=,tag:JL94BWgoq4aFepaSLvF4wQ==,type:str]
    TYPESENSE_API_KEY: ENC[AES256_GCM,data:hv1cnNwDB4fdTtKAl0pBjq+qGyUSa3oLOES6uivntYM=,iv:tJ1xneeY683f4wCOFtOFFzgMK8z+HZ9kIW+pvkowW6s=,tag:D4U3MTEloHR8/PNhBhNTMA==,type:str]
    #ENC[AES256_GCM,data:2naRbtX4y1g9rvvNVoY=,iv:QORTyOAf1uK+AwR/pAYxFrWnKpzSphhhA+DXpHVPCgM=,tag:ARixQB+bzy8VraCCMETTKQ==,type:comment]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:Df7p6LDXJaD7OYeHQjhrtA==,iv:ubdyBgrXooENbXAPHFQVRf6wQLYIxSzwdy/3tcL/8Mc=,tag:WOrGPAuLXzhSJDMB0VeOGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqTWo2UkpZSHVpZGNwQ0c5
            MEFJOXRNbFJyd0lrVDZtbWd5Si8wb2sxY1JFCis5MDBvSWg4eHYzdCt2R09zaG1Z
            MHJIU2lPWHQ1dXlyTWNNdXJNTFc1S0kKLS0tIDNqUHdEZ2VlR25UYzVHRjdlNVdY
            ZUs2a05NaCs0TVN1cUVEcXNFVkRoVGsKBvkC9uYBpQpPD5H6TsT258NNi8XA8Str
            GHXcF3EXYNejzhJXPOwkn+x7hNGLsB9StRBR1y9uV9mfmTdOKdulkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T08:41:08Z"
    mac: ENC[AES256_GCM,data:cMibA0gbM/DRorD5fa8qdqfbR44cCIxdHundf8fHhgxbkQUqyeiuvWgcNEsmlJupt9/l2HbEr4dgbix7aQntZ8ZOcJVkau90X/CVshlFGEh9yJhrcK4KunIAYhTwOK2EibLRuLE6w6gLXTO8R1Joq81gjHFxPJ1rfbvEb69Mlug=,iv:bKg/p77QwSbi5P68tUmPrH8XypIr19h0O3G1/RyeRrU=,tag:4xo0gp9SOoXfGd5ck+DpWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
