apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temporal-local-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN_2}"
    external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
    nginx.ingress.kubernetes.io/enable-websocket: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: external
  tls:
    - hosts:
        - temporal.${SECRET_DOMAIN_2}
      secretName: temporal-tls-secret
  rules:
    - host: temporal.${SECRET_DOMAIN_2}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: temporal-local
                port:
                  number: 8233
