---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app listmonk-app
  namespace: business
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        # strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.9
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: listmonk-secrets
        containers:
          main:
            image:
              repository: listmonk/listmonk
              tag: latest
              pullPolicy: Always
            env:
              TZ: Asia/Ho_Chi_Minh
              LISTMONK_app__admin_username: ""
              LISTMONK_app__admin_password: ""
              LISTMONK_db__host:
                valueFrom:
                  secretKeyRef:
                    name: listmonk-secrets
                    key: INIT_POSTGRES_HOST
              LISTMONK_db__user:
                valueFrom:
                  secretKeyRef:
                    name: listmonk-secrets
                    key: INIT_POSTGRES_USER
              LISTMONK_db__password:
                valueFrom:
                  secretKeyRef:
                    name: listmonk-secrets
                    key: INIT_POSTGRES_PASS
              LISTMONK_db__database:
                valueFrom:
                  secretKeyRef:
                    name: listmonk-secrets
                    key: INIT_POSTGRES_DBNAME
            command:
              - sh
              - -c
              - ./listmonk --install
    service:
      main:
        controller: main
        ports:
          http:
            port: 9000

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: listmonk-secrets
          nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "subcribe.${SECRET_DOMAIN}"
            paths:
              - path: /
                name: main
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
