---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app listmonk-app
  namespace: business
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: Recreate
        annotations:
          secret.reloader.stakater.com/reload: "listmonk-secrets"
        containers:
          main:
            image:
              repository: listmonk/listmonk
              tag: latest
              pullPolicy: Always
            env:
              TZ: Asia/Ho_Chi_Minh
            envFrom:
              - secretRef:
                  name: listmonk-secrets
            command:
              - sh
              - -c
              - ./listmonk
      hookjob:
        enabled: true
        type: job
        annotations:
          helm.sh/hook: "post-install,post-upgrade"
          helm.sh/hook-delete-policy: "hook-succeeded,before-hook-creation"
          helm.sh/hook-weight: "-1"
        replicas: 1
        containers:
          db-migrate-job:
            image:
              repository: listmonk/listmonk
              tag: latest
              pullPolicy: IfNotPresent
            command:
              - ./listmonk
              - --upgrade
            env:
              TZ: Asia/Ho_Chi_Minh
            envFrom:
              - secretRef:
                  name: listmonk-secrets
    service:
      main:
        controller: main
        ports:
          http:
            port: 9000

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "subcribe.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
