# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: listmonk-secrets
    namespace: business
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:x8uRbRXSb5s=,iv:BnwfCT8+dxqKUyo+vfHf7m1GHxJak22CJQG0cKeI45E=,tag:qqDyUQOQHEqSunw1Nsk8/w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:pt7YMD1QiNMtC26R2cHXn7Qv3YbTVz/BGvV762UOy32hW3cg6Cc=,iv:qfiLsbG7fe4K26fNRiL4fz7kNStlZV1DDhVMusRDqzs=,tag:e7RdQIXdq6H5ClXQffcGgg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:YBpe9XztCIs=,iv:lSy69SP4FaqQsBpEsfPLH5PlYz9xjCYeZp1TfilskEs=,tag:Xfr8c8kVzEN7BHCxU91TWw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Pisqd0Al7/WLYpMgLLE=,iv:4dKSJlHua9kVhdOdBGHh/EYgp1nYBBJyqwidQjZQ0kU=,tag:c/txZzrQ06qSEyXJ8tbWzw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:sj21IfH7WVMlmzi+LSdYdA==,iv:Avn3W23sufnAOskSAEBdQ8T9YIus4D3SoBHmKNfFKmo=,tag:wFxVaSP7HGVtXvvLXbafRA==,type:str]
    #ENC[AES256_GCM,data:ZrwjDWzoLa1FSnmLsvdfZru+bfA=,iv:qYjxoaXX2qst2QgYWIQF7EppHDA2xv3MxCSKGJmvCKs=,tag:6D2pQHT+M2MXs6tqhZxSVg==,type:comment]
    auth: ENC[AES256_GCM,data:LY39Ra2ARDQscdgx8R/Kn7E0xvKHMvuwcwHHGRIySWXK0oCWeukF8caS,iv:SLsCw2Vz87+U1lv94NwzeCKYXEbE6k0Yn22C/X3tf+E=,tag:CjSnMfCme8tRI19eyB/UQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-16T00:02:38Z"
    mac: ENC[AES256_GCM,data:4AsFFbix0Fvlsm1dy1mXR6o7wrAaKDUVdbpSjvJKT+qFRYimRnn2jKnKY7RDbrhBRVvVvJ88pkp50qrBfdB23a7L9cR9JDxtbxAD8P97jAZDyQuc5Ax+agL1gbeuaRwZv30r3Q10gYz/Tv60V2MXH4ZnfCKOz2G5k5PdV/ZAedc=,iv:q37TbihzMKkK30ssnxkHhHKEDQceq3nP4TMZoQSoVX4=,tag:WxqdqxmL7tEeq/u7ePuqqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
