apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-data
  namespace: seafile
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-zfs-1
  resources:
    requests:
      storage: 500Gi # Size does not matter
