---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dify-redis
  namespace: ai-apps
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 18.9.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    architecture: standalone
    auth:
      existingSecret: dify-redis-secrets
      existingSecretPasswordKey: redis-password
    master:
      serviceAccount:
        create: true
        name: dify-redis
      persistence:
        enabled: false
