# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: dify-redis-secrets
    namespace: ai-apps
stringData:
    redis-password: ENC[AES256_GCM,data:2B7DyPBqdieuKxytSQw=,iv:l/rU0MxjvEMqdmuSRGCz9fzZtSritQlcRvR7UiJ74DM=,tag:t/04wjoNyvIMy/vK1DmKGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-28T07:41:35Z"
    mac: ENC[AES256_GCM,data:yEnu6HDTpKxoEE/YzIjGgnrAQatBFvFQEvrha+oOOVSTSji+kR9DisntQuZF6DSuZqDD62sPJOvhWtWg0VLsJXr6+BQeb88AH3abyP16JuOgDqjHNB6BMn1ZsfHvmtE6K2Td+FiH+8hr/Z0YKA8gU0aAhOl2rSdeKlwowAB6Y3k=,iv:1ejyUFHNfmR8LJccBjvVe86F/jEZATBvLanm/FCl3G4=,tag:bCCHTMN2CQ/AsZvR+bvdEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
