# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: vector-aggregator-secret
    namespace: monitoring
stringData:
    GEOIPUPDATE_ACCOUNT_ID: ENC[AES256_GCM,data:TJf0foLy,iv:TYSBm1kDYJH+oK/q5dyUXx0loiDpNLkl5AvREv+V7cs=,tag:gr93Pha6Pqx9NJgz4CjuhQ==,type:str]
    GEOIPUPDATE_LICENSE_KEY: ENC[AES256_GCM,data:+NhqrPf8NBaEPBKsbWwV8a/50vXUQpJqfqM0UiLW08WfjepNGY9p7A==,iv:KFuIZury4IiIhl/JWhKLD/elE0a4ABUjnuuoMmQzD64=,tag:c27rUGi+WBLiN+sp01WZjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-11T14:15:00Z"
    mac: ENC[AES256_GCM,data:vvE69ZkTRoy/4Zxyv0S1DDCqLVRS5ydiY1Gnq0nShNu/u7KlwWoAoZ475TLwDuww65eQiFdhJZHuDxkGf7LSJWVTK0/uqwnQmRJ/nci1SN80D3cz1xK36u0zQ4MNB3LFOgY1SKfLj8MV+AsY0mDh/X+qwo7hobG/Ak68mcxzZdo=,iv:jL3oXAXUJ8FGxmTudOaJlAlAPh/JdQJhnYM+nxqYie4=,tag:XUNBbu1iuzWdKzOlZeeFkw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
