# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: memos-secret-envs
    namespace: business
stringData:
    MEMOS_DRIVER: ENC[AES256_GCM,data:7DitdWDNHTM=,iv:8LbJpXWJyXm2glV/wFQ8YsPZrhXyTMj+iVwEboTj1Iw=,tag:bFF7t0JWFSx10KtY6Lf6wg==,type:str]
    MEMOS_DSN: ENC[AES256_GCM,data:e9nDt1IVhJN7SQcFz75Pb7enYV4ZXTBWRtvKjKfgzervJWHl+4N6Fd5zeirrsXY7HzTJEILjnKO1zYWr/MOUWTdZTqg1M46muMk/4ywe3m2/014=,iv:T7KaIfQa5V98Sbbjp1aPzxqghXx9IaK0wVgbYr429H8=,tag:mRVOspzvEykhrgishtiO+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-24T08:37:20Z"
    mac: ENC[AES256_GCM,data:JZzZpyXAA0rdzqn1tPD2/Vz8tck7H4ggqHsFG8CmsyhYyz8gw/9u5x8b5I1WQANBa1H0Myo7Wb6WPngK7JcWEOiqaScQHYpG3b/vziBbGN/BzQc9dF5/xNVc1vpViK/GT59m2RT/b1FQZs36YAm4lKo70W86lidxnoBsjL5z7HE=,iv:zimqUHtQhB9WEQ8N1QkC3soTCL8lMauEBMsn/rrmkPQ=,tag:3TY2g8C2rO3lMtT1g9EZUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
