---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-games-openmu-startup
  namespace: flux-system
spec:
  targetNamespace: openmu
  path: ./kubernetes/apps/games/openmu/startup
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
