---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudnative-pg-shared-root-cluster-gatus-ep
  namespace: database
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: pg-shared-root-cluster
        group: database
        url: tcp://shared-root-postgres-rw.database.svc.cluster.local:5432
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
