apiVersion: v1
kind: Secret
metadata:
    name: frigate-secret
    namespace: frigate
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Yj1Vmw==,iv:JFw9TNSvq/mNLKf8tD37OvwjmSbToJOVBAbdWemUYOk=,tag:fsl6OOEFe30gQbJ2oB/wpA==,type:comment]
    PLUS_API_KEY: ENC[AES256_GCM,data:i68SHpTfMOEcw+va752kJkft9ttvl/8PHR3mk9pHaZQhjZWNI9qLHurb7EnMrhGI,iv:gZKCyLdZpkYlkgT2Buqqb0bNX6w+5sQIyz80gYUDhuM=,tag:jg5vty7PeaLEprz00BZCdQ==,type:str]
    #ENC[AES256_GCM,data:2aPrOCFs2DvhYQ==,iv:0oBLJK2t+JRKGig8so81DJJqPfIdCVtcSXOGgbrCX+Y=,tag:QWskg1CL8JgD1tjtLR0WmA==,type:comment]
    FRIGATE_MQTT_USERNAME: ENC[AES256_GCM,data:NlI7Tg==,iv:xsg9n/MXZz+PUunwQkEC+nNbIAJkfWN2M6APpxOBt1U=,tag:aPTT4KJRyBpfVZtRhgoZUQ==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:Oc+2gNKQunKTcGu7a9zEMA==,iv:kWLsXYnhfK/Nf7zgkxLVzXsxkz+9lUF48Ge/UvREMWE=,tag:2Wm5rKU+HS0Bkf/X1uscjw==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:xGlkpWphNYGpXzAhbA==,iv:KUspCIhey4BbFR6NBl+M9M4pLSNVZ2QPSW6cVQW0p2g=,tag:WY0Db3xM21wyGVh/sfgLeA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ak1YREVWaExOSlhQdHY2
            eEJrbkxuN2w5ZlpLb2p5K1ZKTjB0dUtyNmtrCkVnR1d5Q2wvcFpxREFTR0J5Y25X
            MmNoTlJTU3FHM0U2NjlVa1M2N3htdzAKLS0tIEN3WC9panVjajRQeGVDaVd2VTdC
            SmpXTjBpcWc3YUkrZUVIaFhEY0dLUWsKnjATWrFkR+cyBIiCj4wS5mbLyMh4niSS
            l6gPYoItK7WggTAa+AQl8eeSxbvAPufT4mpSrHsUKuK7gJ+zaeI5oA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-06T08:26:27Z"
    mac: ENC[AES256_GCM,data:cFvLHFjmX6hCKgglQfZ587Hze32z/IY6PVu6iBqX+CqRsiIKDGLbQBgOeigk4JdmNqKhj/uvMTJxS71SBA2lOgguDE1kxBDLgFa1YYjp/YttOyZ1juxg0Q6Zt/vtSJKC+5O6Pt2Q/qE4XajQ4IDgkBrjlj+8fh1Yy9kSqCGX7wE=,iv:EXDP3y/KnUeDq6pXwwb9a2PZbrC4TxnmniDPqQVEsO4=,tag:jpeznQzj2Zcbw5Uv+rrAmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
