---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app stirling-pdf-app
  namespace: business
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: frooodle/s-pdf
              tag: latest
              pullPolicy: Always
            env:
              DOCKER_ENABLE_SECURITY: true
            envFrom:
              - secretRef:
                  name: stirling-pdf-secret-envs
            # resources:
            #   requests:
            #     cpu: 200m
            #     memory: 300Mi
            #   limits:
            #     cpu: 2000m
            #     memory: 3000Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "pdf-tools.${SECRET_DOMAIN}"
            paths:
              - path: /
                name: main
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    # persistence:
    #   config:
    #     enabled: true
    #     globalMounts:
    #       - path: /configs
    #         readOnly: false
    #     storageClass: ceph-block
    #     accessMode: ReadWriteOnce
    #     size: 100Gi
