# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: stirling-pdf-secret-envs
    namespace: business
stringData:
    SECURITY_ENABLE_LOGIN: ENC[AES256_GCM,data:5aYwLw==,iv:BdiPaxoh2YyBkO7SvwJp5pmRQn68Yz5NYmJX8fpdIjI=,tag:O0e9PZ1h0Ygi2DlmY8faPw==,type:bool]
    SECURITY_INITIALLOGIN_USERNAME: ENC[AES256_GCM,data:mwyMnQ==,iv:3ONpFK0QaXzzr4FdXdDDvUFSZr15VfAVu9QggyI52tI=,tag:q86D3W6Q1o9/9AmDM93ulw==,type:str]
    SECURITY_INITIALLOGIN_PASSWORD: ENC[AES256_GCM,data:4FrZAqKUK1apoQj6UCU=,iv:ZEuzwmYNGorq+Dt60H/kuWg0RhMLLAzidg3o/mrU+oM=,tag:cPCzPsCHC2M+sHc08FwhAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T04:47:02Z"
    mac: ENC[AES256_GCM,data:ZGPVxL2IISHS8/pZvNqNzjd98nzRdM77F/nEiJQ5BZCdg7mEY4u64QyCa0r9lC//RQ7w79KEtdRCxfhJHSqHkgys+Kj9tgn1YjLZlD1Tpmo+1Oweyv747jFb3fOWtGRzaoEzZYemdkSyXpPSIQDVbWTa0fx4P3SaXo6ew4BaUzs=,iv:7KdSxx0ubAuxNnhTDud0cpeCDvbDMXYseeencb5g23s=,tag:EbINE0XIztL/vFVneSw/IQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
