# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: stirling-pdf-secret-envs
    namespace: business
stringData:
    SECURITY_ENABLE_LOGIN: ENC[AES256_GCM,data:PlUgdQ==,iv:O1Hp1G3sKhxstmBo3IQoMaZNDgPFuNhtHCtRceGTrWg=,tag:BdHZQmAjunjnqT8cLx1EsA==,type:str]
    SECURITY_INITIALLOGIN_USERNAME: ENC[AES256_GCM,data:mwyMnQ==,iv:3ONpFK0QaXzzr4FdXdDDvUFSZr15VfAVu9QggyI52tI=,tag:q86D3W6Q1o9/9AmDM93ulw==,type:str]
    SECURITY_INITIALLOGIN_PASSWORD: ENC[AES256_GCM,data:4FrZAqKUK1apoQj6UCU=,iv:ZEuzwmYNGorq+Dt60H/kuWg0RhMLLAzidg3o/mrU+oM=,tag:cPCzPsCHC2M+sHc08FwhAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-03T02:28:32Z"
    mac: ENC[AES256_GCM,data:J2MyzKRGf8Gpl3NWdlODb5NN0lUuu+K9ktBZudQOuI8bdoMvjm49T4luxoLgLnNV9J50czQFEAOdheu0PknYQHQmHsHauafpZQD8HXkIMcpaVgbXtxoewU8hL9yqKSisBEbpae5fgpajl6KdK7O987PzHQ36UEUybdFn9OCMbhY=,iv:9IDlp5JGTwbkrgrsSMGxuaDdI8SNa+/IubON4pLX/bI=,tag:pHDy5HcdAVDjHWfG38lG+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
