---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mattermost-team-edition-gatus-ep
  namespace: mattermost
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: mattermost-team-edition
        group: external
        url: https://chat.${SECRET_DOMAIN_2}/api/v4/system/ping
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
          - "[BODY].status == OK"
        alerts:
          - type: pushover
