---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus-pushgateway
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-pushgateway
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: local-path-provisioner
      namespace: kube-system
  values:
    ingress:
      enabled: true
      className: "external"
      annotations:
        nginx.ingress.kubernetes.io/auth-type: basic
        nginx.ingress.kubernetes.io/auth-secret: pushgateway-nginx-auth
        nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
      hosts:
        - &host "pushgateway.${SECRET_DOMAIN}"
      tls:
        - secretName: pushgateway-tls
          hosts:
            - *host
    serviceMonitor:
      enabled: true
      namespace: monitoring
      additionalLabels:
        release: kube-prometheus-stack
