---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vitess-operator
  namespace: flux-system
spec:
  path: ./kubernetes/apps/database/vitess/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-vitess-main-cluster
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-vitess-operator
  path: ./kubernetes/apps/database/vitess/main-cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
