# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: superset
stringData:
    password: ENC[AES256_GCM,data:FltkYr+JyjVfJqIU2nI=,iv:PurDzUz4VaH+sYIGVXBAlgjhV12Su+dHpwMtq857fZY=,tag:PXU75a4sPqqX+WOe15hEuA==,type:str]
    redis-password: ENC[AES256_GCM,data:c3A0+1LweSQZdGlkXx0=,iv:3qYQR0uzYlfhblFZNGOxOfOOmxQvOBLMx+ZsRk928TQ=,tag:Adj2JgLongHNa8be9R9NjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbDNFNXVkOHl6NWlyTDJv
            RExEQ3Y3bThBVU55UlZUQ0FOeEFuekVJTUM0ClRsdW5OK2RCRHN0eU4wc3RmTVJ3
            Titrcm05clA3TGVmUVI0Ym53eXZQOXMKLS0tIERkaDVuREROYW1hdzVtZXhJblNG
            MFQxb25kaS83L1BFSTBTNmtKR2dLV00KAH5EAMySchFaPUfWU0iZ0EFjPxlmGgXx
            rzlnU6BSCZ6cFmTghq2d8vY1wxMrf47RzFJRtZYXy2r6gonVbLyhng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T00:27:49Z"
    mac: ENC[AES256_GCM,data:4EA+QSX2nX3tNn46hqg7Kef5vxNnY90FM3NMHon2c517TQktZzaZCAoacC6BQKnrMBR4IptLJp02rUvmwDtVQJWBAeHwHaMvedWy77TJf6vl1mV4gVsxRYe2YZ6nmPXs781BetP3ChUKrtLukvD3NcIUYUj3+O8nzpGOblN/u68=,iv:yfSr3z4aFoonzZpXsbZrfbN49vyzPhyw74SxEOpFDEU=,tag:MJ2nnVOPzy4UrEdSvWHQUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
