# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: superset
stringData:
    db-host: ENC[AES256_GCM,data:o/PzA/UaocOJNLpqUIiVJWxtTXpHAqk7u0w6yJgFHEGofM/8Il0=,iv:aVvcBM0K9xbuap0T1DCUT84sspeFYFczx+KzkhZ8HFM=,tag:I92iGI4XknXRit7aQd8XQg==,type:str]
    password: ENC[AES256_GCM,data:FltkYr+JyjVfJqIU2nI=,iv:PurDzUz4VaH+sYIGVXBAlgjhV12Su+dHpwMtq857fZY=,tag:PXU75a4sPqqX+WOe15hEuA==,type:str]
    redis-password: ENC[AES256_GCM,data:c3A0+1LweSQZdGlkXx0=,iv:3qYQR0uzYlfhblFZNGOxOfOOmxQvOBLMx+ZsRk928TQ=,tag:Adj2JgLongHNa8be9R9NjA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbDNFNXVkOHl6NWlyTDJv
            RExEQ3Y3bThBVU55UlZUQ0FOeEFuekVJTUM0ClRsdW5OK2RCRHN0eU4wc3RmTVJ3
            Titrcm05clA3TGVmUVI0Ym53eXZQOXMKLS0tIERkaDVuREROYW1hdzVtZXhJblNG
            MFQxb25kaS83L1BFSTBTNmtKR2dLV00KAH5EAMySchFaPUfWU0iZ0EFjPxlmGgXx
            rzlnU6BSCZ6cFmTghq2d8vY1wxMrf47RzFJRtZYXy2r6gonVbLyhng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T00:23:40Z"
    mac: ENC[AES256_GCM,data:+PRwN9TwCiktm0jDCU3gbjXVAK9JP9+JNI7IWpIhOllSRXvQa6EpT85koAayQGVWHJ2EQa58fLKn92Xa2SjsLcTejKZsQ1TO5YB5V/iCl4DRynPrPbzBfpLFD7OMibNs0AFYer28VkbZd8WbbXr/MEYjaWihaJAM6D12iyuHBBk=,iv:EKnen3kdo1heVzfbOKIjjMCq3nW07VE0DVtUN/nmj9g=,tag:VFZRcm79VXBd+aE7B39USQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
