# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: db-secrets
    namespace: superset
stringData:
    password: ENC[AES256_GCM,data:FltkYr+JyjVfJqIU2nI=,iv:PurDzUz4VaH+sYIGVXBAlgjhV12Su+dHpwMtq857fZY=,tag:PXU75a4sPqqX+WOe15hEuA==,type:str]
    redis-password: ENC[AES256_GCM,data:c3A0+1LweSQZdGlkXx0=,iv:3qYQR0uzYlfhblFZNGOxOfOOmxQvOBLMx+ZsRk928TQ=,tag:Adj2JgLongHNa8be9R9NjA==,type:str]
    secretkey: ENC[AES256_GCM,data:4TIrFGZyy9Ew6yVE/exSrxWimIfzOPblC3bgQaxoPtu/5Zqd24zcHkeBHEC7ZHTbIKk2pjv9NNw=,iv:Clm7i2wm2tzntvI9xECAnAJv1hjR9qsQSO0gOYpkaZs=,tag:8BOzDK35+sLIFrm4NYygrA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbDNFNXVkOHl6NWlyTDJv
            RExEQ3Y3bThBVU55UlZUQ0FOeEFuekVJTUM0ClRsdW5OK2RCRHN0eU4wc3RmTVJ3
            Titrcm05clA3TGVmUVI0Ym53eXZQOXMKLS0tIERkaDVuREROYW1hdzVtZXhJblNG
            MFQxb25kaS83L1BFSTBTNmtKR2dLV00KAH5EAMySchFaPUfWU0iZ0EFjPxlmGgXx
            rzlnU6BSCZ6cFmTghq2d8vY1wxMrf47RzFJRtZYXy2r6gonVbLyhng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-14T00:42:55Z"
    mac: ENC[AES256_GCM,data:rC3/7I6hnuIfAszhDoskHAjRrzqyY4NdKs473nukv4iFepIFKKtH9NxQ2oo8SNdNcD4lxMlql33m7l+qmgCvOT269mzdm9FV8uHb8OfJ/yQSbpdHvLZBPH+MLGiVBovjZaEEeAqKZCHZclMEjfai6t7e/It6fbmzwej61GxDMRM=,iv:NWK4bA+btEwg9x5/djPtz+n8FCuh6augYu5/qnQXWtI=,tag:BGPy4FK1gpvb121mlHs67g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
