---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app chat-server-dapr
  namespace: openmu-prod
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: "daprio/daprd:latest"
              tag: latest
            command:
              [
                "./daprd",
                "-app-id",
                "chatServer",
                "-app-port",
                "8080",
                "-components-path",
                "/components",
                "-config",
                "/components/config.yaml",
                "-placement-host-address",
                "dapr-placement.openmu-prod.svc.cluster.local:50006",
              ]
            # resources:
            #   requests:
            #     cpu: 200m
            #     memory: 300Mi
            #   limits:
            #     cpu: 2000m
            #     memory: 3000Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080

    ingress:
      main:
        enabled: false

        persistence:
      dapr-components:
        enabled: true
        type: configMap
        name: dapr-components-config
        globalMounts:
          - path: /components/config.yaml
            subPath: config.yaml
          - path: /components/localSecretStore.yaml
            subPath: localSecretStore.yaml
          - path: /components/login-state.yaml
            subPath: login-state.yaml
          - path: /components/pubsub.yaml
            subPath: pubsub.yaml
      secrets:
        type: secret
        name: app-secrets
        globalMounts:
          - path: /components/secrets.json
            subPath: dapr-secrets.json
