---
apiVersion: v1
kind: Service
metadata:
  name: erpnext-gunicorn
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: gunicorn
    app.kubernetes.io/instance: erpnext-app
    app.kubernetes.io/name: erpnext-app
