---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app erpnext-app
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        # strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: frappe/erpnext
              tag: v15.24.1
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: erpnext-app-env-secrets
            args:
              - nginx-entrypoint.sh
            probes: &probes
              # -- Liveness probe configuration
              # @default -- See below
              liveness:
                # -- Enable the liveness probe
                enabled: true
                # -- Set this to `true` if you wish to specify your own livenessProbe
                custom: false
                # -- sets the probe type when not using a custom probe
                # @default -- "TCP"
                type: TCP
                # -- The spec field contains the values for the default livenessProbe.
                # If you selected `custom: true`, this field holds the definition of the livenessProbe.
                # @default -- See below
                spec:
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3

              # -- Readiness probe configuration
              readiness:
                # -- Enable the readiness probe
                enabled: true
                # -- Set this to `true` if you wish to specify your own readinessProbe
                custom: false
                # -- sets the probe type when not using a custom probe
                # @default -- "TCP"
                type: TCP
                # -- The spec field contains the values for the default readinessProbe.
                # If you selected `custom: true`, this field holds the definition of the readinessProbe.
                # @default -- See below
                spec:
                  initialDelaySeconds: 5
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            # resources:
            #   requests:
            #     cpu: 200m
            #     memory: 300Mi
            #   limits:
            #     cpu: 2000m
            #     memory: 3000Mi
        # initContainers:
        #   permission:
        #     image:
        #       repository: public.ecr.aws/docker/library/busybox
        #       tag: latest@sha256:650fd573e056b679a5110a70aabeb01e26b76e545ec4b9c70a9523f2dfaf18c6
        #       pullPolicy: IfNotPresent
        #     command:
        #       - "/bin/sh"
        #       - "-c"
        #       - chown -R 1000:1000 /home/frappe/frappe-bench/sites
      socketio:
        replicas: 1
        containers:
          main:
            image:
              repository: frappe/erpnext
              tag: v15.24.1
            args:
              - node
              - /home/frappe/frappe-bench/apps/frappe/socketio.js
            probes: *probes
      scheduler:
        replicas: 1
        containers:
          main:
            image:
              repository: frappe/erpnext
              tag: v15.24.1
            args:
              - bench
              - schedule
      worker-default:
        replicas: 1
        containers:
          main:
            image:
              repository: frappe/erpnext
              tag: v15.24.1
            args:
              - bench
              - worker
              - --queue
              - default
            probes: &worker-probes
              # -- Liveness probe configuration
              # @default -- See below
              liveness:
                # -- Enable the liveness probe
                enabled: true
                # -- Set this to `true` if you wish to specify your own livenessProbe
                custom: true
                # -- The spec field contains the values for the default livenessProbe.
                # If you selected `custom: true`, this field holds the definition of the livenessProbe.
                # @default -- See below
                spec:
                  exec:
                    command:
                      - bash
                      - -c
                      - echo "Ping backing services";
                      - wait-for-it vietwings-erp-mariadb.database.svc.cluster.local:3306 -t 1;
                      - wait-for-it erpnext-app-redis-cache-master.business.svc.cluster.local:6379 -t 1;
                      - wait-for-it erpnext-app-redis-queue-master.business.svc.cluster.local:6379 -t 1;
                  initialDelaySeconds: 15
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 3

              # -- Readiness probe configuration
              readiness:
                # -- Enable the readiness probe
                enabled: true
                # -- Set this to `true` if you wish to specify your own readinessProbe
                custom: true
                # -- The spec field contains the values for the default readinessProbe.
                # If you selected `custom: true`, this field holds the definition of the readinessProbe.
                # @default -- See below
                spec:
                  exec:
                    command:
                      - bash
                      - -c
                      - echo "Ping backing services";
                      - wait-for-it vietwings-erp-mariadb.database.svc.cluster.local:3306 -t 1;
                      - wait-for-it erpnext-app-redis-cache-master.business.svc.cluster.local:6379 -t 1;
                      - wait-for-it erpnext-app-redis-queue-master.business.svc.cluster.local:6379 -t 1;
                  initialDelaySeconds: 15
                  periodSeconds: 5
                  timeoutSeconds: 1
                  failureThreshold: 3
      worker-short:
        replicas: 1
        containers:
          main:
            image:
              repository: frappe/erpnext
              tag: v15.24.1
            args:
              - bench
              - worker
              - --queue
              - short,default
            probes: *worker-probes
      worker-long:
        replicas: 1
        containers:
          main:
            image:
              repository: frappe/erpnext
              tag: v15.24.1
            args:
              - bench
              - worker
              - --queue
              - long,default,short
            probes: *worker-probes
      gunicorn:
        replicas: 1
        containers:
          main:
            image:
              repository: frappe/erpnext
              tag: v15.24.1
            probes: *probes
    service:
      main:
        controller: main
        ports:
          http:
            port: 8080
      gunicorn:
        controller: gunicorn
        ports:
          http:
            port: 8000
      socketio:
        controller: socketio
        ports:
          http:
            port: 9000

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "vietwings-erp.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: ImplementationSpecific
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      worker:
        enabled: true
        existingClaim: ${APP}
        globalMounts:
          - path: /home/frappe/frappe-bench/sites
            readOnly: false
