---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./helm-release.yaml
  # - ./socketio-service.yaml
  # - ./gunicorn-service.yaml
  - ../../../../templates/volsync
