# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: erpnext-app-env-secrets
stringData:
    CLIENT_MAX_BODY_SIZE: ENC[AES256_GCM,data:U8VF,iv:jh85mia+sTiPaR3jFxfZ0ZIXO5konE6GS7fUth5m4UQ=,tag:03XEA3GE2ou6xb5cVZWrHA==,type:str]
    REDIS_CACHE: ENC[AES256_GCM,data:5luxOay/MuKeqn2xQquEVfMoa+fpLX9jT3pAqj28fasvFmM6VmPdZ0hJQssmCGEPL7241WnPm0kb/ThPL+DItYOxK1Wt9g==,iv:0Qm7NU2tBZsDkoZG8S2rFz7m2k1gjhL8HcBIZnebzcw=,tag:ugcF/i4NP8+hWpAyv+2fHA==,type:str]
    REDIS_QUEUE: ENC[AES256_GCM,data:YpEb4rEHmMM6AQkDs4PCQ1psLKVCJWuVZhhfrbDvzHrUPG/rAVvZDGSLLfUyU4drdJSWM/wg3HtxZx46xW033SEgfng3Sg==,iv:EjqJAvYPVoC93ibZkLBG2BVyRGbx6HNbQkNhmTqd0Gw=,tag:3LVJMRDsAA0pcnuYpMIR3A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T04:35:55Z"
    mac: ENC[AES256_GCM,data:4fat4lXRY+PxNFhRyLCsX9P87qzrbsK2e66yzvgXQbHGRidRd9uwUdUnBRCVfERxOvWxkJCkAOQ49yeUAUQ1wRQWrnzmvha5Aw0KO4sdW6QpIUR0d4Ztc9/XcbjxTKbAn7RAI9HbPwPco98sTH0qF2IAlryWCA6TJ/p7qeIkVic=,iv:u5/PvKObvIjsg/OXPjRVxTjKQUjAKSEMLckxncSe36g=,tag:EVYNIT+ZXn6yxazXNqG6GQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
