# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: erpnext-app-env-secrets
stringData:
    CLIENT_MAX_BODY_SIZE: ENC[AES256_GCM,data:U8VF,iv:jh85mia+sTiPaR3jFxfZ0ZIXO5konE6GS7fUth5m4UQ=,tag:03XEA3GE2ou6xb5cVZWrHA==,type:str]
    REDIS_CACHE: ENC[AES256_GCM,data:5luxOay/MuKeqn2xQquEVfMoa+fpLX9jT3pAqj28fasvFmM6VmPdZ0hJQssmCGEPL7241WnPm0kb/ThPL+DItYOxK1Wt9g==,iv:0Qm7NU2tBZsDkoZG8S2rFz7m2k1gjhL8HcBIZnebzcw=,tag:ugcF/i4NP8+hWpAyv+2fHA==,type:str]
    REDIS_QUEUE: ENC[AES256_GCM,data:YpEb4rEHmMM6AQkDs4PCQ1psLKVCJWuVZhhfrbDvzHrUPG/rAVvZDGSLLfUyU4drdJSWM/wg3HtxZx46xW033SEgfng3Sg==,iv:EjqJAvYPVoC93ibZkLBG2BVyRGbx6HNbQkNhmTqd0Gw=,tag:3LVJMRDsAA0pcnuYpMIR3A==,type:str]
    FRAPPE_REDIS_CACHE: ENC[AES256_GCM,data:EQ83JjYYR6RHNtPzOZv/7Zp101TWd+JoP1P+hEzHCCtjnS+evaRo21Q71xVz6py2NkSWCWXPDLe5VN3NPdJ1bn2zw9YQiA==,iv:lyqPGn38d+ODrkjCyobfqKfEjDENihA8OfL4YXHvbnk=,tag:FRKE7WvRwQMSJJKebyppew==,type:str]
    FRAPPE_REDIS_QUEUE: ENC[AES256_GCM,data:1wKd653TbYczm5ys8KP2WguBJ8LDNlw8k/WYY53pi6YwkACZ2a7iZk/T3uJ5+feMCma0SjT3SIz4hPFUy1z9GYS35Nqzgw==,iv:Xc6bIyFY+ULCcWCm//n2bKrqkSruDMqP6hQ4y40Cea4=,tag:goHhd1iB0WVZLvEGrLzutQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T05:01:04Z"
    mac: ENC[AES256_GCM,data:kBdBm86YQdAb4sYzekf++SUkV8HF/R96j/KpdawLYohjOh75lWxvMpHMOthe2jn/JapnMI4r94ZX1FbeIpnlrwqy5Q3WyoK7dnZFNgqxKG4G7Qwt8yiRG2MnVoXxNFfJJ1pDj1CXFxpKcmLZ5sF7qKWJ8szB/o5sRiCeqlD+vUg=,iv:Adkx2DQNZouSFqzuMYJebjrVsHA/MNqP1iaRGc5SxDQ=,tag:ciGQnhGV5LP5mjzjlpZ4bA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
