# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: erpnext-app-env-secrets
stringData:
    CLIENT_MAX_BODY_SIZE: ENC[AES256_GCM,data:U8VF,iv:jh85mia+sTiPaR3jFxfZ0ZIXO5konE6GS7fUth5m4UQ=,tag:03XEA3GE2ou6xb5cVZWrHA==,type:str]
    REDIS_CACHE: ENC[AES256_GCM,data:5luxOay/MuKeqn2xQquEVfMoa+fpLX9jT3pAqj28fasvFmM6VmPdZ0hJQssmCGEPL7241WnPm0kb/ThPL+DItYOxK1Wt9g==,iv:0Qm7NU2tBZsDkoZG8S2rFz7m2k1gjhL8HcBIZnebzcw=,tag:ugcF/i4NP8+hWpAyv+2fHA==,type:str]
    REDIS_QUEUE: ENC[AES256_GCM,data:YpEb4rEHmMM6AQkDs4PCQ1psLKVCJWuVZhhfrbDvzHrUPG/rAVvZDGSLLfUyU4drdJSWM/wg3HtxZx46xW033SEgfng3Sg==,iv:EjqJAvYPVoC93ibZkLBG2BVyRGbx6HNbQkNhmTqd0Gw=,tag:3LVJMRDsAA0pcnuYpMIR3A==,type:str]
    FRAPPE_REDIS_CACHE: ENC[AES256_GCM,data:EQ83JjYYR6RHNtPzOZv/7Zp101TWd+JoP1P+hEzHCCtjnS+evaRo21Q71xVz6py2NkSWCWXPDLe5VN3NPdJ1bn2zw9YQiA==,iv:lyqPGn38d+ODrkjCyobfqKfEjDENihA8OfL4YXHvbnk=,tag:FRKE7WvRwQMSJJKebyppew==,type:str]
    FRAPPE_QUEUE_CACHE: ENC[AES256_GCM,data:vNvjgBkb3/vZd4BYkul8sA+VgiKk/6p8e2WkAXtMDttm95Y/WQAXkjBwiQt6MJQ3wW1+J9ifk6hNCcgT0uZ3KGO1lJ5IFg==,iv:tBnDX+lgqTx6ZdmCmSG7F5pPbI7HWkwPrHVYcwqUZUw=,tag:mQZzAcLkfZUGslCFMAHGWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T04:57:33Z"
    mac: ENC[AES256_GCM,data:dcYskg1TLJft6tPpDdvhGo8/yHQcsTWEmpLk1C3E9pfSbqV5637STLhkKCGw23EOjY7AUGC8oXb/ggIRWVLp1xrC5koD+ufab9bYx0t2IGWzo2xdBDvQGgCCy2bOPcKqLvg6VPHfzFJWCZrVyrWXsVT+24jfNneb0egrK8lcvDs=,iv:CN8qbLlvNgYhWguzFb1p5gSYPoOVblXdgCQczNX/RoM=,tag:3BHlkaLuDh8FSQPbFKr8rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
