# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: erpnext-app-env-secrets
stringData:
    CLIENT_MAX_BODY_SIZE: ENC[AES256_GCM,data:U8VF,iv:jh85mia+sTiPaR3jFxfZ0ZIXO5konE6GS7fUth5m4UQ=,tag:03XEA3GE2ou6xb5cVZWrHA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-21T04:09:58Z"
    mac: ENC[AES256_GCM,data:hZux7tCUrpOIbxQ/fEaKJF7usVYsEtkwNH/8SRL1/48YANJXW3RaQDpza3Sm29WawDhv0gyb/lcc6N7zyC3evZgoUuH5bspaOaHf9QK+H10BKVGie89k0IARg+/oCz/c5EY6GE/4A5kw9S1/XP9lMeo8/5UERnB/9L9e+3pNcns=,iv:6H2mgKl9o2uILx35oSumPQJ3iowH1Ek9zPbHbUfanMo=,tag:jqGVRWXrMXT39dSJGAg55Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
