---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: staging-postgres
  namespace: database
  annotations:
    kyverno.io/ignore: "true"
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1-15
  enableSuperuserAccess: true
  inheritedMetadata:
    labels:
      kube-image-keeper.enix.io/image-caching-policy: ignore
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: local-path
  superuserSecret:
    name: cloudnative-pg-staging-secret
  postgresql:
    # shared_preload_libraries:
    #   - "vectors.so"
    parameters:
      max_connections: "600"
      shared_buffers: 512MB
  monitoring:
    enablePodMonitor: true
