---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app coder-v2
  namespace: coder-v2
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.7.2
      sourceRef:
        kind: HelmRepository
        name: coder-v2
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    coder:
      env:
        - name: CODER_ACCESS_URL
          value: "https://coder.${SECRET_DOMAIN}"
      ingress:
        enable: true
        className: external
        host: &host "coder.${SECRET_DOMAIN}"
        wildcardHost: "*-coder.${SECRET_DOMAIN}"
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        tls:
          enable: true
          secretName: "coder-tls-secret"
          wildcardSecretName: "wildcard-coder-tls-secret"
