# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: coder-v2
stringData:
    pgurl: ENC[AES256_GCM,data:GQ4rbc7zmfm9VZXVA5i6MOPBpcs1pmQwew0rR1nymRvXXKZjjP3bF8h+0EKYwzGLoKs/wv8QeJSx09vmiURrwueLKW5gz3Y3RIdpiOKpbuFjSgU6lAU8jmhLjGXiJa1wkhLz9Co=,iv:J3epTyew3ySrKYHAUDQK8GSGTo3gAe1u2KAKpywNb6o=,tag:uZPtuaclt74Dfsewk26Y7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MTlLNm9Ca01WcHA5dE5i
            SVUwbm96MmZiTXNFSzNNR2JGbmtvTXgrQmhVCnlsazc3RjJUbU02RXo3SU95QzMx
            UklNM0xaaWV1S3hNVm5uWndwR0VTNkkKLS0tIGpLUVBvNFpqaUZYRUhiUGlSbGhI
            OFNjT2x5RG9yM3MvSkFzVnVJeGJoWWMKCxMMlNQpXtiW2izYYtdzvL4cKjcaQHhQ
            +vH1OB1xcWZdbyvRicYtAD6N0BfbEx1Ep42u+eSfSXybFpxtmDeT5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-25T06:54:01Z"
    mac: ENC[AES256_GCM,data:S/0MlcXQ56Xuai/w1khCxrrsxm+iYXTii+gpnqZQovLmPy8JbQqCw2YPQA36D1SSZR6XCNwyeJZkDrv74NUxzoakijmyYvtPLKKFJDNsn6QdzutxXH8LsZD+B2EsOS8pfzJr1QJQbDAI0I1y1nujAearWpW9YLbrz6qO65XWCjQ=,iv:za/n9r6Hz+9DvNr/IfDFLK0Z1mIfQQJoSUSGQmfcydQ=,tag:xLezWpZGjfJLbszEP9y5ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
