---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: locatepin-redis
  namespace: business
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 18.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # global:
    #   storageClass: local-path
    architecture: standalone
    auth:
      existingSecret: locatepin-redis-secrets
      existingSecretPasswordKey: redis-password
    master:
      # podSecurityContext:
      #   fsGroup: 65534
      # containerSecurityContext:
      #   runAsUser: 65534
      #   runAsGroup: 0
      serviceAccount:
        create: true
        name: locatepin-redis-master
      persistence:
        enabled: false
