# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: locatepin-redis-secrets
    namespace: business
stringData:
    redis-password: ENC[AES256_GCM,data:d96FWXYeM2Cj+G1vUvS2uQ==,iv:+a7lnsaa+XksPdJ6loOXaINTmzuFoEZSdVSPjiRTqKY=,tag:4IBx3whEwzQMU1UZl+CVpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-26T07:29:03Z"
    mac: ENC[AES256_GCM,data:+Sqp1AOxAoIXIbHOG+JuJwENhFtsEMqmdnWBdvfsWUk+Sk81vhBb13SBgEDB4Y3JcuLdFiBtyzTG0huZxfZ3xD9g+MFH/EQ4E/KzEBz0cpToKe8JwbNOGB+7fFgAP2OpukwIvsXM2t/CRfNWhslJrVlBT9GSn7cfQJjmXrB8uU8=,iv:OieyvXX85wca52dey9BbnrFuzZ9XWxTuSvSf2IIiWNo=,tag:5/Lk2NEXl3QcqDrYNhBtFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
