---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-development-coder-workspace
  namespace: flux-system
spec:
  targetNamespace: development
  path: ./kubernetes/apps/development/coder-workspace/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
