---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-local-tenant
  namespace: local-minio
spec:
  interval: 15m
  chart:
    spec:
      chart: tenant
      version: 5.0.11
      sourceRef:
        kind: HelmRepository
        name: minio-operator
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    secrets:
      existingSecret:
        name: minio-local-tenant-env-configuration
    tenant:
      name: local-minio
      configuration:
        name: minio-local-tenant-env-configuration
      pools:
        - servers: 4
          name: pool-0
          volumesPerServer: 1
          size: 100Gi
          storageClassName: local-path
          resources:
            requests:
              memory: 4Gi
            limits:
              memory: 12Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsNonRoot: true
          containerSecurityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
      subPath: /data
      # additionalVolumes:
      #   - name: old-data
      #     persistentVolumeClaim:
      #       claimName: minio
      #       namespace: minio
      # additionalVolumeMounts:
      #   - mountPath: /old-data
      #     name: old-data
      metrics:
        enabled: true
      buckets:
        - name: data
          objectLock: false
      certificate:
        requestAutoCert: false
    ingress:
      api:
        enabled: true
        ingressClassName: external
        # labels: {}
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN_2}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        host: &apihost "local-s3.${SECRET_DOMAIN_2}"
        tls:
          - secretName: local-minio-ingress-tls
            hosts:
              - *apihost
        path: /
        pathType: Prefix
      console:
        enabled: true
        ingressClassName: external
        # labels: {}
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN_2}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        host: &consolehost "console.local-s3.${SECRET_DOMAIN_2}"
        tls:
          - secretName: local-minio-console-ingress-tls
            hosts:
              - *consolehost
        path: /
        pathType: Prefix
