---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: locatepin-backend
  namespace: business
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        strategy: RollingUpdate
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.1
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: locatepin-secrets
        containers:
          main:
            image:
              repository: ghcr.io/imtoanle/locatepin-server
              tag: 0.0.2 #DO_NOT_REMOVE_TAG_INDICATOR

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8888
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: false
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      # limits:
      #   memory: 500Mi
    persistence:
      config:
        enabled: true
        type: "configMap"
        name: "locatepin-backend-config"
        globalMounts:
          - path: /app/config.yaml
            subPath: config.yaml
      # uploads:
      #   enabled: true
      #   globalMounts:
      #     - path: /app/uploads
      #       readOnly: false
      #   storageClass: rook-ceph
      #   accessMode: ReadWriteOnce
      #   size: 1Gi
