---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ${APP}-redis
spec:
  interval: 15m
  chart:
    spec:
      chart: redis
      version: 22.0.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: true
        storageClass: ${PERSISTENCE_STORAGE_CLASS:-ceph-block}
        size: ${PERSISTENCE_SIZE:-8Gi}
    networkPolicy:
      enabled: true
      allowExternal: false
      extraIngress:
        - ports:
            - protocol: TCP
              port: 6379
          from:
            - podSelector:
                matchLabels:
                  app.kubernetes.io/instance: ${APP}
                  app.kubernetes.io/name: ${APP}
