---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_3/./-}-production"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN_3/./-}-production-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_3}"
  dnsNames:
    - "${SECRET_DOMAIN_3}"
    - "*.${SECRET_DOMAIN_3}"
