---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN_3/./-}-staging"
  namespace: networking
spec:
  secretName: "${SECRET_DOMAIN_3/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN_3}"
  dnsNames:
    - "*.${SECRET_DOMAIN_3}"
