---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: obsidian-couchdb
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      obsidian-couchdb:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

        initContainers:
          init-config:
            image:
              repository: public.ecr.aws/docker/library/busybox
              tag: latest@sha256:2f590fc602ce325cbff2ccfc39499014d039546dc400ef8bbf5c6ffb860632e7
              pullPolicy: IfNotPresent
            command:
              - "/bin/sh"
              - "-c"
              - "cp /tmp/config/*.ini /opt/couchdb/etc/default.d/; ls -lrt /opt/couchdb/etc/default.d;"

        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/couchdb
              tag: 3.3.3
            envFrom:
              - secretRef:
                  name: obsidian-couchdb-secret
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5

    service:
      app:
        controller: obsidian-couchdb
        ports:
          http:
            port: 5984

    ingress:
      app:
        className: external
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN_2}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
        hosts:
          - host: &hostName "obsd.${SECRET_DOMAIN_2}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: obsidian-couchdb-ingress-tls
            hosts:
              - *hostName

    persistence:
      config:
        enabled: true
        type: configMap
        name: obsidian-couchdb-configmap
        advancedMounts:
          obsidian-couchdb:
            init-config:
              - path: /tmp/config
      data:
        enabled: true
        existingClaim: obsidian-couchdb
        advancedMounts:
          obsidian-couchdb:
            app:
              - path: /opt/couchdb/data
      config-storage:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /opt/couchdb/etc/default.d
