# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: obsidian-couchdb-secret
stringData:
    COUCHDB_USER: ENC[AES256_GCM,data:zBZYANhQteQ=,iv:/dQraRwMm3hKSgfT/smjgH+21cUn2zbISfjo1UG3xMc=,tag:u4B00ZHkG/TH83P7xIHR8A==,type:str]
    COUCHDB_PASSWORD: ENC[AES256_GCM,data:Yl9Llad2l/JuQ/z3t6A=,iv:5gQdEViOJdu1zv9VFIiwV7XYoPL58RGSBb7PYM9CRFo=,tag:v2rLoPOAzP5QQ2fEaYrOVQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-09T04:13:39Z"
    mac: ENC[AES256_GCM,data:Ie9GXbs1oDabU/SVwFSElyTCFsUyOtoQv291og5whDku3Wzjp8qdQ4oUQg2UudJhWepfmtDgRA9FFf3kzgbL+aJnPW+aTyOHL7jZxF3dNFGfvkEbbUhhZ4b969fTMmV+5PdRe3JJvQ/vNyNQNGLe1BIfIcT0AHmSUxJ48kpKF5A=,iv:E5ALbdN05AjdN81Y9hBDUYvUG9Z4YJwvE5lLmV8C7kc=,tag:xA2XL26O//Ve0AICRELYlw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
