---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-business-chatwoot-aitbase-prod
  namespace: flux-system
spec:
  targetNamespace: business
  dependsOn:
    - name: cluster-apps-cloudnative-pg-cluster
  path: ./kubernetes/apps/business/chatwoot/aitbase/prod/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: chatwoot-aitbase-prod
      INGRESS_DOMAIN: livesupport.${SECRET_DOMAIN}
