# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-vietwings-secret-envs
    namespace: business
stringData:
    ACTIVE_STORAGE_SERVICE: ENC[AES256_GCM,data:UhEePeYMuamlxFOsgg==,iv:bPzFbhoE2aBDDst38JVMXqZSdLMhw4W1N6J0H3FDf24=,tag:R86cY642FJSHWrcnVI30bg==,type:str]
    STORAGE_BUCKET_NAME: ENC[AES256_GCM,data:CiFhLU68RgAu7JFedPb34v6Z,iv:AG0QpG2BPM5/SXFNZr1R/sFV7zgb1xJ+yYoN+7JdfRA=,tag:JdyYK5EjZZlaJP0rEiAv9w==,type:str]
    STORAGE_ACCESS_KEY_ID: ENC[AES256_GCM,data:VrnXhdEWnQfeL5CvMrtoh401tig=,iv:oIQl2w8O8xXJyK2UR1uXMvSZkzBq1gy0hwYpS0hKQEY=,tag:WIcRMe12QD+gX5tBeDmpzw==,type:str]
    STORAGE_REGION: ""
    STORAGE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IEN7S3ZZLsnT8iCNImu0vJgR3xJ0PZlR7Chi4sDgGJdR1K/fXneENA==,iv:og302KWYBWxQm0dkC4Tcf9wg+hlgKtkqwzNjjHxar3E=,tag:oUqD4k2tgeY04jo5lMcJUw==,type:str]
    STORAGE_ENDPOINT: ENC[AES256_GCM,data:Tylrqyo7nRAJyrD0yOY6Eov3YVY4Ohizo6GDwY7D,iv:uEtI2ABx1AO/J3w7uDRQIeoFB7JXGkfy0pDbLh5aNsc=,tag:1J/QBeJ1v1/USpdLoeaQBA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:m39RwvuFsbWfgyzCZJCrupGg76J692fjRhjCp+q18d3PYMqcPU95mBVGqbrPE1EXDZoc,iv:L6XWXQVgJ+lCJfJcRW8DAuiAd78BlMS753h4kGtTOdY=,tag:XqQsE+sgS/094o/ODzL8dQ==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:lhZa4g==,iv:k1oV5GVhWB5YPg00wsLJjVGFJ1hKVZDKEp2MTZwt/LA=,tag:H1kCCjQLzK8O4DLPgrVvEg==,type:str]
    REDIS_PASSWORD: ""
    POSTGRES_HOST: ENC[AES256_GCM,data:jvfFmvPTri+Xqb8LUZkQGmzuqU+bqxX/Ia8C8E4Ttj/RffUje6I=,iv:wahqqzZb0nBhXB78Tpsne1XY/RbaTXkANvlFk/qVGmU=,tag:rZaMOjNpz/zHbJSHrIcKAA==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:dmheVA==,iv:Ff7K98S7x5Nmmm63BENAsFBUOlKBN9H1xXFws7xe+qg=,tag:hge4gnEa/un6cOlrZr2Ykg==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:OSgP9ufG+PCN0fHYMkQByBj4,iv:p7IVMCEknUcYnZ5Zztrp1f8VnFQZecFtiyvrmfSMev8=,tag:K95pp4mGnA2LAo7CGkKNwA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Elx71kXvkA5uBMryJymGBA==,iv:+AWPLJB8jOGyVGYHB+OVQqhs7fsRlYPPUoPPVzp3ODE=,tag:ye2z49jhYIJ+y/8cooyQRw==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:VsFkjg6iDlUn22dPFlzFleFZ,iv:+ucR519nOgm1W+lEohh1MlkmYSRyEyBSh/GbrGN3LRw=,tag:ipmTBR0YyZ/cun9afdyzkA==,type:str]
#   ANDROID_BUNDLE_ID: com.chatwoot.app
#   ANDROID_SHA256_CERT_FINGERPRINT: "AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8"
#   ASSET_CDN_HOST: ""
#   ENABLE_ACCOUNT_SIGNUP: false
#   FB_APP_ID: ""
#   FB_APP_SECRET: ""
#   FB_VERIFY_TOKEN: ""
#   FORCE_SSL: false
#   FRONTEND_URL: https://support.aitbase.com
#   INSTALLATION_ENV: helm
#   IOS_APP_ID: "6C953F3RX2.com.chatwoot.app"
#   LOG_LEVEL: info
#   LOG_SIZE: "500"
#   MAILER_INBOUND_EMAIL_DOMAIN: ""
#   MAILER_SENDER_EMAIL: ""
#   MAILGUN_INGRESS_SIGNING_KEY: ""
#   MANDRILL_INGRESS_API_KEY: ""
#   RAILS_ENV: production
#   RAILS_INBOUND_EMAIL_PASSWORD: ""
#   RAILS_INBOUND_EMAIL_SERVICE: ""
#   RAILS_LOG_TO_STDOUT: true
#   RAILS_MAX_THREADS: "5"
#   REDIS_URL: "redis://chatwoot-vietwings-redis.business.svc.cluster.local:6379"
#   REDIS_SENTINEL_MASTER_NAME: ""
#   REDIS_SENTINELS: ""
#   REDIS_TLS: false
#   SECRET_KEY_BASE: e1a36dac86b0715d9f68d3cf4bb315c82bb6a1b57fc0cc1af4fa440aa04e53915a81474347997973f39590e0798fe2960f9ec41367ccf272ac66df691602dd06
#   SENTRY_DSN: ""
#   SLACK_CLIENT_ID: ""
#   SLACK_CLIENT_SECRET: ""
#   SMTP_ADDRESS: ""
#   SMTP_AUTHENTICATION: plain
#   SMTP_ENABLE_STARTTLS_AUTO: true
#   SMTP_OPENSSL_VERIFY_MODE: none
#   SMTP_PASSWORD: ""
#   SMTP_PORT: "587"
#   SMTP_USERNAME: ""
#   TWITTER_APP_ID: ""
#   TWITTER_CONSUMER_KEY: ""
#   TWITTER_CONSUMER_SECRET: ""
#   TWITTER_ENVIRONMENT: ""
#   USE_INBOX_AVATAR_FOR_BOT: true
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T04:38:25Z"
    mac: ENC[AES256_GCM,data:wD/g+9e7gysuSZgmHWYF7cgYzwLHQoPvyFQlDwt2KEyGaivYrGRVN889J0xMT5r3nR/qHlbsoivSmovhMzAwQma9VUWNF3knDgIpq68IQbHtZRi9iY6VvDxiFhfA5v4vle8ag+r9X0Mov/OlzzXc2u06G5JmqFBzjzKe9W9FIA4=,iv:4GJ8m6ERoOXUIq9BYn405Gyzi44PhRGiEsGX7ly72nU=,tag:IFd5p2vtqdlXqTZPZyIvaw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
