# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-vietwings-secret-envs
    namespace: business
stringData:
    ACTIVE_STORAGE_SERVICE: ENC[AES256_GCM,data:UhEePeYMuamlxFOsgg==,iv:bPzFbhoE2aBDDst38JVMXqZSdLMhw4W1N6J0H3FDf24=,tag:R86cY642FJSHWrcnVI30bg==,type:str]
    STORAGE_BUCKET_NAME: ENC[AES256_GCM,data:CiFhLU68RgAu7JFedPb34v6Z,iv:AG0QpG2BPM5/SXFNZr1R/sFV7zgb1xJ+yYoN+7JdfRA=,tag:JdyYK5EjZZlaJP0rEiAv9w==,type:str]
    STORAGE_ACCESS_KEY_ID: ENC[AES256_GCM,data:VrnXhdEWnQfeL5CvMrtoh401tig=,iv:oIQl2w8O8xXJyK2UR1uXMvSZkzBq1gy0hwYpS0hKQEY=,tag:WIcRMe12QD+gX5tBeDmpzw==,type:str]
    STORAGE_REGION: ""
    STORAGE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:IEN7S3ZZLsnT8iCNImu0vJgR3xJ0PZlR7Chi4sDgGJdR1K/fXneENA==,iv:og302KWYBWxQm0dkC4Tcf9wg+hlgKtkqwzNjjHxar3E=,tag:oUqD4k2tgeY04jo5lMcJUw==,type:str]
    STORAGE_ENDPOINT: ENC[AES256_GCM,data:Tylrqyo7nRAJyrD0yOY6Eov3YVY4Ohizo6GDwY7D,iv:uEtI2ABx1AO/J3w7uDRQIeoFB7JXGkfy0pDbLh5aNsc=,tag:1J/QBeJ1v1/USpdLoeaQBA==,type:str]
    ANDROID_BUNDLE_ID: ENC[AES256_GCM,data:jUovB9WQZDMAAY34dfHHlw==,iv:eJ7L9y92GHo/L9HuIgpALUT/VI6yXXkTBQDosvW9Iy8=,tag:/yqn6FWoocW0Sy3GWzyciA==,type:str]
    ANDROID_SHA256_CERT_FINGERPRINT: ENC[AES256_GCM,data:pn0arwKJAfdEmWyqrPPcZ1JnJNAfQZrEP5EtWyfqpz9f2Tj6f/BFuE991B7PgTukQsQ/TLArqKyRJVP6VXyXeu6Mt3SLRk74HPR2Jg8YBqHpxv6ATNKkz9ZAaoemS+E=,iv:5bYJVNwU/79kUjXwDdWCRqVYynQlsIsCx+vSnGI7GTg=,tag:3fVKqxUXBPm56iEjzr+fFA==,type:str]
    ASSET_CDN_HOST: ""
    ENABLE_ACCOUNT_SIGNUP: ENC[AES256_GCM,data:ncv+fbY=,iv:h1Vm0PgxOme2GICi8vi/wEjrO4c3OUCMDM0SmMyNRO0=,tag:hSoniX7tRAq1PsY6jq6rEA==,type:bool]
    FB_APP_ID: ""
    FB_APP_SECRET: ""
    FB_VERIFY_TOKEN: ""
    FORCE_SSL: ENC[AES256_GCM,data:RKeESoQ=,iv:53/WOkZGtl4hxM6l5dPNdFHj/gmY0fg7d288aSoA0g0=,tag:kv8gHy27lB0t+8xUbDkgow==,type:bool]
    FRONTEND_URL: ENC[AES256_GCM,data:fE5olb9bg4bNFsok9k5oDFNpJBw5ZQPF80fa,iv:lz/x+K43fkE1V7xvoIJrp3hi9Rb9BYEX6l1ve5kYjhE=,tag:oyE0YbCWBFaynkOAQ59hrg==,type:str]
    INSTALLATION_ENV: ENC[AES256_GCM,data:pHPN+w==,iv:KhOLj95dRGQXlSO9LPFt4opNxI4FX4SolGL3tdvVDCA=,tag:n9asgnAl6RRvTgnrQm7DVA==,type:str]
    IOS_APP_ID: ENC[AES256_GCM,data:s0zGR3N3P8UUaPIwq8rBhEiF2eI92ah9ZftT,iv:cpTGPTHJqM3VHuQwGD5rsEspgqR0bAKGPrLlcKQD1B4=,tag:EgtPDfAdqbi+ULJ/9NfUgg==,type:str]
    LOG_LEVEL: ENC[AES256_GCM,data:6/VT4w==,iv:OiUXwoLtqp0iFAktGTYYWlD7nsaeDZZCNvEJXyIJLTs=,tag:1n803N97HXN+2AWUlkwDhQ==,type:str]
    LOG_SIZE: ENC[AES256_GCM,data:uStu,iv:mwv9Q4NtrjBfP4Fdt7yArvOZ3OrBRX00K6dviRjY4z8=,tag:BRE1mNfCrl0ly2BDCmdMxQ==,type:str]
    MAILER_INBOUND_EMAIL_DOMAIN: ""
    MAILER_SENDER_EMAIL: ""
    MAILGUN_INGRESS_SIGNING_KEY: ""
    MANDRILL_INGRESS_API_KEY: ""
    RAILS_ENV: ENC[AES256_GCM,data:tUandwccVwDRBA==,iv:l6KFbNN7uoHKGx3Qg6X3w6P37zh5gmJo20Y2lEn8uhY=,tag:vyt0fYTS3DBxY66Gkm3Mxw==,type:str]
    RAILS_INBOUND_EMAIL_PASSWORD: ""
    RAILS_INBOUND_EMAIL_SERVICE: ""
    RAILS_LOG_TO_STDOUT: ENC[AES256_GCM,data:Vg2uxg==,iv:nmaxmJF3nPkHWR1Por6i4byYAagv7KwMgo8VDN63yy0=,tag:PABkuyqWZXHqV+fR1BkT0g==,type:bool]
    RAILS_MAX_THREADS: ENC[AES256_GCM,data:ag==,iv:jfJTxzOXKHfN5g0FVBlbjefaUA+Hu9QqX1h+NrpcfjU=,tag:4zgHDTTcOw+TdmFvjTwRZA==,type:str]
    POSTGRES_HOST: ENC[AES256_GCM,data:jvfFmvPTri+Xqb8LUZkQGmzuqU+bqxX/Ia8C8E4Ttj/RffUje6I=,iv:wahqqzZb0nBhXB78Tpsne1XY/RbaTXkANvlFk/qVGmU=,tag:rZaMOjNpz/zHbJSHrIcKAA==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:dmheVA==,iv:Ff7K98S7x5Nmmm63BENAsFBUOlKBN9H1xXFws7xe+qg=,tag:hge4gnEa/un6cOlrZr2Ykg==,type:str]
    POSTGRES_USERNAME: ENC[AES256_GCM,data:OSgP9ufG+PCN0fHYMkQByBj4,iv:p7IVMCEknUcYnZ5Zztrp1f8VnFQZecFtiyvrmfSMev8=,tag:K95pp4mGnA2LAo7CGkKNwA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Elx71kXvkA5uBMryJymGBA==,iv:+AWPLJB8jOGyVGYHB+OVQqhs7fsRlYPPUoPPVzp3ODE=,tag:ye2z49jhYIJ+y/8cooyQRw==,type:str]
    POSTGRES_DATABASE: ENC[AES256_GCM,data:VsFkjg6iDlUn22dPFlzFleFZ,iv:+ucR519nOgm1W+lEohh1MlkmYSRyEyBSh/GbrGN3LRw=,tag:ipmTBR0YyZ/cun9afdyzkA==,type:str]
    REDIS_HOST: ENC[AES256_GCM,data:m39RwvuFsbWfgyzCZJCrupGg76J692fjRhjCp+q18d3PYMqcPU95mBVGqbrPE1EXDZoc,iv:L6XWXQVgJ+lCJfJcRW8DAuiAd78BlMS753h4kGtTOdY=,tag:XqQsE+sgS/094o/ODzL8dQ==,type:str]
    REDIS_PORT: ENC[AES256_GCM,data:lhZa4g==,iv:k1oV5GVhWB5YPg00wsLJjVGFJ1hKVZDKEp2MTZwt/LA=,tag:H1kCCjQLzK8O4DLPgrVvEg==,type:str]
    REDIS_PASSWORD: ""
    REDIS_URL: ENC[AES256_GCM,data:6dj88QXIwTQLJWKj5Bh+TnN9tRHFqXlYukspzVNoHK+WpGm9mQ5CbLLpjVx5k6vglYv6vFyJ0f40Nw1TwJArKg==,iv:RTWAEb47rhEBt+yO+otd811Y9/dIw4Ne8ibmn2OpzKw=,tag:Ly05cjUZFDzcEOnj+Yte2g==,type:str]
    REDIS_SENTINEL_MASTER_NAME: ""
    REDIS_SENTINELS: ""
    REDIS_TLS: ENC[AES256_GCM,data:oyzKIUQ=,iv:fJVx9IZoir68vb4fgk3Nf7YcP91xtwmmtwfOVME+lx8=,tag:olEK0rISHP7tsD9ftGGXHg==,type:bool]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:SL3UROSz2AsIsn2ZmOY2DPkG1tm07EFTgE2OmhxfENsnytCejTUiqwWFWzNduVRgiyTWF1n5cqD3PzpTZf0wYgnnR4Z2HPcTJZkkcVYHw7b56I8Sm37OxvX2/i3UEkD1PmPYyEbm/h4hbXdYUP+cy8i5IWxuSLvBol0D0g5u5Xc=,iv:yLhtzjyTZLIEJE+wn5FNZ4RPwz2d+/VJR/8oXC8Pgz0=,tag:2GDJFU3/QKWJ3hlcvrnExg==,type:str]
    SENTRY_DSN: ""
    SLACK_CLIENT_ID: ""
    SLACK_CLIENT_SECRET: ""
    SMTP_ADDRESS: ""
    SMTP_AUTHENTICATION: ENC[AES256_GCM,data:gWmkTqU=,iv:VvIJnKwP8W7a/9phBvoBxQiccb9coLG30qWm4YUvOMI=,tag:snoX7yeIWCJ6Ik1F0AUhsA==,type:str]
    SMTP_ENABLE_STARTTLS_AUTO: ENC[AES256_GCM,data:A9AVJw==,iv:Xoe8w8KvMNsjkd8BYcFH6QUKxfd1LZwAqW9NT2VxEtM=,tag:sdElPpbrpm/Q/m7OU6CTnA==,type:bool]
    SMTP_OPENSSL_VERIFY_MODE: ENC[AES256_GCM,data:kd4hOQ==,iv:+8Ad+07cJ9Tymnmfl+LeBv1H7TgH3/xc3bT+qmlYTco=,tag:dZdzF/SP9CKNvwp1nVlx0w==,type:str]
    SMTP_PASSWORD: ""
    SMTP_PORT: ENC[AES256_GCM,data:eocT,iv:rAjUm89juTu+zJ6J/5AUGBe4czu/mHB/wPh+rsQk50s=,tag:IqZ01HIJHMtFuB1oHoRr1w==,type:str]
    SMTP_USERNAME: ""
    TWITTER_APP_ID: ""
    TWITTER_CONSUMER_KEY: ""
    TWITTER_CONSUMER_SECRET: ""
    TWITTER_ENVIRONMENT: ""
    USE_INBOX_AVATAR_FOR_BOT: ENC[AES256_GCM,data:sqvbWQ==,iv:fguWejq583oKRyoc7sc8giX90sIa4STsvIM1zyuyhtg=,tag:mUlEMHoJnOXSAaV/waszRg==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-21T04:20:27Z"
    mac: ENC[AES256_GCM,data:OF6lAJjgOLrfIj8hm+1zZF4zuU9Oj0QsZ6FfvzKHDc4pu92+vViHLAiA2pOJ4GQ64Yo4DxAWNg0EtcnnMyapCnuMFVUfH23bvG671tyQ+ZI4C7+AoTneHpxzgOYSneVqSWexAW2ZRGZwJrONY8Rl9bhIFLK0UcYMiQ3Y0bbBwbg=,iv:enoLZeaSr9q0+s3skvjgiPy0MP2smxJp0we9C08D2os=,tag:l0fn5NkyNAzZMy+DklV7bQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
