# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: langflow
stringData:
    app.username: ENC[AES256_GCM,data:x8h+FA==,iv:zUYPgGJpbeAS9QdjUyBjT0jK8OdDo28ujiOcXEdTHRU=,tag:9R4d9LXJoS5pYV+LjsJjfA==,type:str]
    app.password: ENC[AES256_GCM,data:Cl9iZPQ/2CEZx0Y862IA6w==,iv:N4S5k91KHgmgLUFFTMysJeJzApVOY5/c6s0ndCtOzmU=,tag:gYWVhQZ0zsIqwJm5rH1mxw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-01T02:37:47Z"
    mac: ENC[AES256_GCM,data:ukNkqYjtk7mAuzlEy2WDwHHF3rjG52+9MJDwfvtE6Ih3tzPEhu57CRqdQD5E63jzocBAEDKliyvNF/aCvyNng9oAozOuNQ5mHKOXFg73V+Ee10jT6Dm/MJ3DZB5GQ4zH8SUELm1lwdkYVRZQxa/fueXn9hO+XO9YrDxqQv0M/t0=,iv:QDDOHACXx/yMTP2XNH0UnnhdHDXyR7oTSNsyk2t77AU=,tag:4yiyuPrFWCDygyTY969v5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
