# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:5D9MqA==,iv:COJi0CQDeqgnD7dlHdx1sGV3cUeuGvCO25WgK+R+TFI=,tag:lAWvEnuOBz7dYPJgrHIssQ==,type:str]
    password: ENC[AES256_GCM,data:IfNC9nXr0Nge0gidvHZ2qg==,iv:2GZZAv6X58NvQ1dd7/qNYyn5L+twI+kBYi/ZqSJCE3k=,tag:izpD7HNDtTj49TpPo611TA==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:Z5Ut2Td/LRMbQcjZmu4uQLby8Vf5d1Xao+XLmFrN3W0=,iv:rYcuxxf+WJYAmGoEX16ukjNZwh/YW0TtAbr/fZd7Ox4=,tag:rsktWPSbtNj2Zuo6SylVXw==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:0HZHfM8Pmv6WJ0G3fU1M3kg1CGjpbA/T+A6m/O8kV3kyKAu2dWkOFS26nS+utoXt7p4QXwWjfFZ+DIJSz4B1+w==,iv:r65QjkI5MHVltxQ3c6Is4WdRxYCD6VBEK9S0Pd3Haxc=,tag:+ANJoaazdZGyU6Zfsgi07g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MTlLNm9Ca01WcHA5dE5i
            SVUwbm96MmZiTXNFSzNNR2JGbmtvTXgrQmhVCnlsazc3RjJUbU02RXo3SU95QzMx
            UklNM0xaaWV1S3hNVm5uWndwR0VTNkkKLS0tIGpLUVBvNFpqaUZYRUhiUGlSbGhI
            OFNjT2x5RG9yM3MvSkFzVnVJeGJoWWMKCxMMlNQpXtiW2izYYtdzvL4cKjcaQHhQ
            +vH1OB1xcWZdbyvRicYtAD6N0BfbEx1Ep42u+eSfSXybFpxtmDeT5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T07:03:37Z"
    mac: ENC[AES256_GCM,data:fZTmjv19mEAEoV86nxB9OdSUm9RG4nBZIkOE8bbqtE2VZppp5iVDh+o4H1hf8p0GodwLgA4zrvb5SG4WVKQP36ECKav0Jnsig2awXZo8UCThBMY1BL84fVfNPRXxqsYpBAocU4mUcMKqJ/tMgf6JHrgg4uLo0sTQ7cnuVnKZizE=,iv:rRdOAJdVeWsygwxdfKcNswlfPsqBJD0WhO3g5TiYQ9Q=,tag:YbB8qskyOZzCleoPGF+Gpw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
