---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app hoppscotch-app
  namespace: development
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.4
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        strategy: Recreate
        annotations:
          secret.reloader.stakater.com/reload: "hoppscotch-secret-envs"
        containers:
          main:
            image:
              repository: hoppscotch/hoppscotch
              tag: 2024.3.0
              pullPolicy: Always
            envFrom:
              - secretRef:
                  name: hoppscotch-secret-envs
    service:
      main:
        controller: main
        ports:
          http:
            port: 5230

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "restc.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
