# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-openmu-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:DjF+b8YM4qY=,iv:ASvSsDeZ6DheUYyrPkVUTl/rdDHASskFkyzqni6VXMI=,tag:tnCCNCa3Nj4uyQCS62ixWw==,type:str]
    password: ENC[AES256_GCM,data:bw1U7lWtwvciLuGVwVI=,iv:BHTKhfk0+8yoxiohF/AXaY/v4+CdsTwBAFZktW0oIGs=,tag:H+FfRe8fiNyD8NuOLfL9aw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MTlLNm9Ca01WcHA5dE5i
            SVUwbm96MmZiTXNFSzNNR2JGbmtvTXgrQmhVCnlsazc3RjJUbU02RXo3SU95QzMx
            UklNM0xaaWV1S3hNVm5uWndwR0VTNkkKLS0tIGpLUVBvNFpqaUZYRUhiUGlSbGhI
            OFNjT2x5RG9yM3MvSkFzVnVJeGJoWWMKCxMMlNQpXtiW2izYYtdzvL4cKjcaQHhQ
            +vH1OB1xcWZdbyvRicYtAD6N0BfbEx1Ep42u+eSfSXybFpxtmDeT5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-20T23:59:41Z"
    mac: ENC[AES256_GCM,data:rJnxN2tLzdQZPiDHreq4tgepreL5X/llwH9HKbwXf+hZj8ICcFsjildecCDAZzDvZmn/g67HdQjMpX2TSJHlXNey0M1ovIU2m60oUOpIpDkiiAaEhZrtaJDnawfRfPNc8Ehh1hd9Yt/snId0Nx93CBsCo/ZWtN5UAcePGxSekic=,iv:xW15HkSxiB5qfL/93nIdqtyUL31+tBMhwImHWEgXyeM=,tag:sF75NyhYkWVP/7qA++slJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
