---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app dapr-app
  namespace: dapr-system
spec:
  interval: 30m
  chart:
    spec:
      chart: dapr
      version: 1.12.4
      sourceRef:
        kind: HelmRepository
        name: dapr
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    dapr_rbac:
      secretReader:
        enabled: true
        namespace: dapr-system
