---
apiVersion: v1
kind: ConfigMap
metadata:
  name: windmill-gatus-ep
  namespace: windmill
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: windmill
        group: external
        url: https://windmill.${SECRET_DOMAIN}/api/version
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover
