---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app ${APP}
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.1.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        # strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/gis-ops/docker-valhalla/valhalla
              tag: latest@sha256:b6aa2687028f86878d8f37e6d45029e345a724f453bc3f24e6c21c73327c2945
            env:
              tile_urls: https://download.geofabrik.de/asia/vietnam-latest.osm.pbf
              use_tiles_ignore_pbf: "True"
              force_rebuild: "True"
              build_elevation: "False"
              build_admins: "True"
              build_time_zones: "False"
              build_transit: "False"
              build_tar: "True"
              # server_threads: "4" # Auto get nproc number
            # resources:
            #   requests:
            #     cpu: 200m
            #     memory: 300Mi
            #   limits:
            #     cpu: 2000m
            #     memory: 3000Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 8002

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: &host "valhalla.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: ${APP}
        globalMounts:
          - path: /custom_files
            readOnly: false
