---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-seafile-memcached
  namespace: flux-system
spec:
  path: ./kubernetes/apps/storage/seafile/memcached
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-seafile-app
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-mariadb-seafile-instance
    - name: cluster-apps-storage-seafile-memcached
  path: ./kubernetes/apps/storage/seafile/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-seafile-office
  namespace: flux-system
spec:
  dependsOn:
    - name: cluster-apps-mariadb-seafile-instance
  path: ./kubernetes/apps/storage/seafile/office
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
