# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: app-secrets
    namespace: seafile
stringData:
    seafile-mariadb-root-password: ENC[AES256_GCM,data:ZthcmhTGYnaivjQ5WHQ=,iv:zWkUaOE1bRRfmF11iGtMCiT6VgstgyDvpIlJYEZTxz0=,tag:eGDlJCGgH+pmivROz2EJzg==,type:str]
    seafile-mariadb-password: ENC[AES256_GCM,data:LF5NvqprY8IgrX5HbaA=,iv:tn/5Ym/BtaO/CNUvxuSxfC9UlATWYWuLmIz75qP+J0A=,tag:7jDjb2CjBKzFojeQ6STiCg==,type:str]
    onlyoffice-mariadb-password: ENC[AES256_GCM,data:aaGWhL80X287ThVx86w=,iv:ccMNGFLMXJiSfvrho3fhMOXkDQq2hvdPCWo1pSzj2Bw=,tag:vs9jkUO4Z5WlzSQ8Gevofg==,type:str]
    app-admin-email: ENC[AES256_GCM,data:ShZGrfyjJYDZnoH2hSZ5YBBabQ==,iv:ygzbihBDOQQhmXZwI4uIVUptpf9hT3NONQSbYswvJL4=,tag:FktiLko0M6IJ6BY4romrWw==,type:str]
    app-admin-password: ENC[AES256_GCM,data:ETvLzfQCB2GKsujf29fS4A==,iv:fNVCld7m/optjBhcvE2i420TUAoyQmJ+LJDtRR9xDOs=,tag:DH9CNU7G+KI7IPwVDUKWlQ==,type:str]
    onlyoffice-jwt-secret: ENC[AES256_GCM,data:blIPYUdkC79Hy1SMaJzOT8/3zJN6J9jA,iv:TytV3HBcdOknR4DRngrXYhnDKfGBJLqDOJGe7vAbPBQ=,tag:Y0Cv1EmIlt6AOMi/55WkWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T00:18:42Z"
    mac: ENC[AES256_GCM,data:Ufh0R19IAYz5AlRfVUomYwhm40AQfZFNyPy/QfMYl1ncFYzqKZh5gYVNT+WFXj1OQQRRugtEZbrssJVl3XZK9g760eNjWIpjuPjLLoiFsQIQ7AeBobr782OliLAeiCDPJ1RysynTTwn4zPKT4NWo6Ho9BhcEEzSQbQnNiHfw4x0=,iv:S5ZksH7YAwCuyncrCz1Oqf3nLbYWZKCWbcRmkWiDZcw=,tag:SUrYHKCMCVpH65unDklwiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
