---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app login-server
  namespace: openmu-prod
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
          dapr.io/enabled: true
          dapr.io/app-id: loginServer
          dapr.io/app-port: 8080
          # dapr.io/env
        containers:
          main:
            image:
              repository: munique/openmu-login
              tag: 0.8.2
            env:
              ASPNETCORE_URLS: http://+:8080
              ASPNETCORE_ENVIRONMENT: Production
            # resources:
            #   requests:
            #     cpu: 200m
            #     memory: 300Mi
            #   limits:
            #     cpu: 2000m
            #     memory: 3000Mi
    service:
      main:
        controller: main
        ports:
          http:
            port: 50001
          # Prometheus
          metrics:
            port: 9464

    ingress:
      main:
        enabled: false
