# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-env-secrets
stringData:
    PAPERLESS_REDIS: ENC[AES256_GCM,data:eXSdGz3SjenDmImN22btbytx7PJL/45N7eaoT6+f8lCk1jl27hXSj8AG7l6gS7eFWUMKSVYD/eA=,iv:k0hmJMDK4UZlcuqpNtkmvEUYKyqSFvhJnmuJjtu+11I=,tag:/zHmFg8nK18FyIhZYcIPEA==,type:str]
    PAPERLESS_DBENGINE: ENC[AES256_GCM,data:buDlAR8RnkByjA==,iv:gf0exGu016o6uuc3pN6j+TL9sx/uDCEvM36UxyM4e+I=,tag:Y++fEIA6NCDy7DXYr7vCfg==,type:str]
    PAPERLESS_DBHOST: ENC[AES256_GCM,data:Hr9OAfhfN6hu07m/Ohwv8eum3GwQnLuIh7VgV4QlyziZznAnEao=,iv:4HRLhhBjG4GYkis23fMaINRShmlK1nrOrK9fp1D8/Gs=,tag:UTWDal1aR8MkG27hFN2ArQ==,type:str]
    PAPERLESS_DBNAME: ENC[AES256_GCM,data:+X6YD+ZXtu6AQS2NEr8=,iv:0bENrpq/JL9olNVOWlUt6ew9EYhoAPGGvmfU9nLHNgU=,tag:CIkQwTj0ud3UvVgoEw9Z+Q==,type:str]
    PAPERLESS_DBUSER: ENC[AES256_GCM,data:JlLJ5fb94yjs,iv:Kdoh2RbDyAzYjwig8Sav2nPalzabPRQq6WLw+tmjb2w=,tag:RdFPvrIPFXzKC5oY/BHoAA==,type:str]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:UodqSvYP56d2QN+xotQ=,iv:3c8uARv+L+90cYZNreCoYZngglzrG6oIhv2ZmKUrLLw=,tag:URlfej+mm3HDpbqCELq+dQ==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:vNvGRU6vQ1515K1enzjbuj+2AIqnfMkYlVaGkMFWFVUQbSrjgz/Ik4gnEVa0yx7d/7R6gVmLGMpvyoGnr/pzvw==,iv:CfLeDWvc36rNxAJ4PKCxw7CfVz8zfm+BULDzNzUdrHM=,tag:lO6aPN9G+VBXYQbfprsYcg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14j28wpn82nnskt0rzcaqxzwnhx33ardgl640rckvwrys8grphvwsyt4ch2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUjQ2NmtLQ1JKVEgwRkdS
            MVZTUnNZWUsvUS9MVWpwb001bXd3L2lJSlhrCkJFajBHNzVobnRWNU5TV2swYnRO
            dEIyNnRpVVVTK01YWU5wZTRPbGN6Y1EKLS0tIGFwYno0aCtybXBLVFc1L2I5VFlB
            eGJtck1sVEVQMi9nZWgvS3hJTm9KWlUKCUUgCNrIGhAfvkFpfoSbyE8y37MS5Bww
            ET2BH5lqLdq35hGdU0jubOFrk4iLyC88x3YEyuIOjrHdf9eCLfQM/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-05T01:58:17Z"
    mac: ENC[AES256_GCM,data:hauHGaY8dMYWLgp/DrLPi1qc4+xtwMX/AOwb7EHj1xS4Ph6VRu1AbH0bt7pNO91nVxHJGMHq+CMDFqkxMMztoiWbXRk3F9KRHntSosUXRjPc28MiPqWRifTFqqdW1wMTcT+7bHVmmg9BHQYHZ9+noyIusb18W1sVkmWBfYfiLds=,iv:war8aB3kUQikGukN8pzNKY6EmUQ0WaAQo2i6dWOu5eY=,tag:asem7XgHfDA5M1e98+mI2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
